// Auto-generated from fonts.google.com/metadata/fonts
// 1911 fonts

const GOOGLE_FONTS: Map<string, string> = new Map([
  ["abeezee", "sans-serif"],
  ["adlam display", "display"],
  ["ar one sans", "sans-serif"],
  ["abel", "sans-serif"],
  ["abhaya libre", "serif"],
  ["aboreto", "display"],
  ["abril fatface", "display"],
  ["abyssinica sil", "serif"],
  ["aclonica", "sans-serif"],
  ["acme", "sans-serif"],
  ["actor", "sans-serif"],
  ["adamina", "serif"],
  ["advent pro", "sans-serif"],
  ["afacad", "sans-serif"],
  ["afacad flux", "sans-serif"],
  ["agbalumo", "display"],
  ["agdasima", "sans-serif"],
  ["agu display", "display"],
  ["aguafina script", "handwriting"],
  ["akatab", "sans-serif"],
  ["akaya kanadaka", "display"],
  ["akaya telivigala", "display"],
  ["akronim", "display"],
  ["akshar", "sans-serif"],
  ["aladin", "display"],
  ["alan sans", "sans-serif"],
  ["alata", "sans-serif"],
  ["alatsi", "sans-serif"],
  ["albert sans", "sans-serif"],
  ["aldrich", "sans-serif"],
  ["alef", "sans-serif"],
  ["alegreya", "serif"],
  ["alegreya sc", "serif"],
  ["alegreya sans", "sans-serif"],
  ["alegreya sans sc", "sans-serif"],
  ["aleo", "serif"],
  ["alex brush", "handwriting"],
  ["alexandria", "sans-serif"],
  ["alfa slab one", "display"],
  ["alice", "serif"],
  ["alike", "serif"],
  ["alike angular", "serif"],
  ["alkalami", "serif"],
  ["alkatra", "display"],
  ["allan", "display"],
  ["allerta", "sans-serif"],
  ["allerta stencil", "sans-serif"],
  ["allison", "handwriting"],
  ["allura", "handwriting"],
  ["almarai", "sans-serif"],
  ["almendra", "serif"],
  ["almendra display", "display"],
  ["almendra sc", "serif"],
  ["alumni sans", "sans-serif"],
  ["alumni sans collegiate one", "sans-serif"],
  ["alumni sans inline one", "display"],
  ["alumni sans pinstripe", "sans-serif"],
  ["alumni sans sc", "sans-serif"],
  ["amarante", "display"],
  ["amaranth", "sans-serif"],
  ["amarna", "sans-serif"],
  ["amatic sc", "handwriting"],
  ["amethysta", "serif"],
  ["amiko", "sans-serif"],
  ["amiri", "serif"],
  ["amiri quran", "serif"],
  ["amita", "handwriting"],
  ["anaheim", "sans-serif"],
  ["ancizar sans", "sans-serif"],
  ["ancizar serif", "serif"],
  ["andada pro", "serif"],
  ["andika", "sans-serif"],
  ["anek bangla", "sans-serif"],
  ["anek devanagari", "sans-serif"],
  ["anek gujarati", "sans-serif"],
  ["anek gurmukhi", "sans-serif"],
  ["anek kannada", "sans-serif"],
  ["anek latin", "sans-serif"],
  ["anek malayalam", "sans-serif"],
  ["anek odia", "sans-serif"],
  ["anek tamil", "sans-serif"],
  ["anek telugu", "sans-serif"],
  ["angkor", "display"],
  ["annapurna sil", "serif"],
  ["annie use your telescope", "handwriting"],
  ["anonymous pro", "monospace"],
  ["anta", "sans-serif"],
  ["antic", "sans-serif"],
  ["antic didone", "serif"],
  ["antic slab", "serif"],
  ["anton", "sans-serif"],
  ["anton sc", "sans-serif"],
  ["antonio", "sans-serif"],
  ["anuphan", "sans-serif"],
  ["anybody", "display"],
  ["aoboshi one", "serif"],
  ["arapey", "serif"],
  ["arbutus", "serif"],
  ["arbutus slab", "serif"],
  ["architects daughter", "handwriting"],
  ["archivo", "sans-serif"],
  ["archivo black", "sans-serif"],
  ["archivo narrow", "sans-serif"],
  ["are you serious", "handwriting"],
  ["aref ruqaa", "serif"],
  ["aref ruqaa ink", "serif"],
  ["arima", "display"],
  ["arimo", "sans-serif"],
  ["arizonia", "handwriting"],
  ["armata", "sans-serif"],
  ["arsenal", "sans-serif"],
  ["arsenal sc", "sans-serif"],
  ["artifika", "serif"],
  ["arvo", "serif"],
  ["arya", "sans-serif"],
  ["asap", "sans-serif"],
  ["asap condensed", "sans-serif"],
  ["asar", "serif"],
  ["asimovian", "sans-serif"],
  ["asset", "display"],
  ["assistant", "sans-serif"],
  ["asta sans", "sans-serif"],
  ["astloch", "display"],
  ["asul", "serif"],
  ["athiti", "sans-serif"],
  ["atkinson hyperlegible", "sans-serif"],
  ["atkinson hyperlegible mono", "sans-serif"],
  ["atkinson hyperlegible next", "sans-serif"],
  ["atma", "display"],
  ["atomic age", "display"],
  ["aubrey", "display"],
  ["audiowide", "display"],
  ["autour one", "display"],
  ["average", "serif"],
  ["average sans", "sans-serif"],
  ["averia gruesa libre", "display"],
  ["averia libre", "display"],
  ["averia sans libre", "display"],
  ["averia serif libre", "display"],
  ["azeret mono", "monospace"],
  ["b612", "sans-serif"],
  ["b612 mono", "monospace"],
  ["bbh bartle", "sans-serif"],
  ["bbh bogle", "sans-serif"],
  ["bbh hegarty", "sans-serif"],
  ["biz udgothic", "sans-serif"],
  ["biz udmincho", "serif"],
  ["biz udpgothic", "sans-serif"],
  ["biz udpmincho", "serif"],
  ["babylonica", "handwriting"],
  ["bacasime antique", "serif"],
  ["bad script", "handwriting"],
  ["badeen display", "display"],
  ["bagel fat one", "display"],
  ["bahiana", "display"],
  ["bahianita", "display"],
  ["bai jamjuree", "sans-serif"],
  ["bakbak one", "display"],
  ["ballet", "handwriting"],
  ["baloo 2", "display"],
  ["baloo bhai 2", "display"],
  ["baloo bhaijaan 2", "display"],
  ["baloo bhaina 2", "display"],
  ["baloo chettan 2", "display"],
  ["baloo da 2", "display"],
  ["baloo paaji 2", "display"],
  ["baloo tamma 2", "display"],
  ["baloo tammudu 2", "display"],
  ["baloo thambi 2", "display"],
  ["balsamiq sans", "display"],
  ["balthazar", "serif"],
  ["bangers", "display"],
  ["barlow", "sans-serif"],
  ["barlow condensed", "sans-serif"],
  ["barlow semi condensed", "sans-serif"],
  ["barriecito", "display"],
  ["barrio", "display"],
  ["basic", "sans-serif"],
  ["baskervville", "serif"],
  ["baskervville sc", "serif"],
  ["battambang", "display"],
  ["baumans", "display"],
  ["bayon", "sans-serif"],
  ["be vietnam pro", "sans-serif"],
  ["beau rivage", "handwriting"],
  ["bebas neue", "sans-serif"],
  ["beiruti", "sans-serif"],
  ["belanosima", "sans-serif"],
  ["belgrano", "serif"],
  ["bellefair", "serif"],
  ["belleza", "sans-serif"],
  ["bellota", "display"],
  ["bellota text", "display"],
  ["benchnine", "sans-serif"],
  ["benne", "serif"],
  ["bentham", "serif"],
  ["berkshire swash", "handwriting"],
  ["besley", "serif"],
  ["beth ellen", "handwriting"],
  ["bevan", "serif"],
  ["bhutuka expanded one", "serif"],
  ["big shoulders", "display"],
  ["big shoulders inline", "display"],
  ["big shoulders stencil", "display"],
  ["bigelow rules", "display"],
  ["bigshot one", "display"],
  ["bilbo", "handwriting"],
  ["bilbo swash caps", "handwriting"],
  ["biorhyme", "serif"],
  ["biorhyme expanded", "serif"],
  ["birthstone", "handwriting"],
  ["birthstone bounce", "handwriting"],
  ["biryani", "sans-serif"],
  ["bitcount", "display"],
  ["bitcount grid double", "display"],
  ["bitcount grid double ink", "display"],
  ["bitcount grid single", "display"],
  ["bitcount grid single ink", "display"],
  ["bitcount ink", "display"],
  ["bitcount prop double", "display"],
  ["bitcount prop double ink", "display"],
  ["bitcount prop single", "display"],
  ["bitcount prop single ink", "display"],
  ["bitcount single", "display"],
  ["bitcount single ink", "display"],
  ["bitter", "serif"],
  ["black and white picture", "display"],
  ["black han sans", "sans-serif"],
  ["black ops one", "display"],
  ["blaka", "display"],
  ["blaka hollow", "display"],
  ["blaka ink", "display"],
  ["blinker", "sans-serif"],
  ["bodoni moda", "serif"],
  ["bodoni moda sc", "serif"],
  ["bokor", "display"],
  ["boldonse", "display"],
  ["bona nova", "serif"],
  ["bona nova sc", "serif"],
  ["bonbon", "handwriting"],
  ["bonheur royale", "handwriting"],
  ["boogaloo", "display"],
  ["borel", "handwriting"],
  ["bowlby one", "display"],
  ["bowlby one sc", "display"],
  ["braah one", "sans-serif"],
  ["brawler", "serif"],
  ["bree serif", "serif"],
  ["bricolage grotesque", "sans-serif"],
  ["bruno ace", "display"],
  ["bruno ace sc", "display"],
  ["brygada 1918", "serif"],
  ["bubblegum sans", "display"],
  ["bubbler one", "sans-serif"],
  ["buda", "display"],
  ["buenard", "serif"],
  ["bungee", "display"],
  ["bungee hairline", "display"],
  ["bungee inline", "display"],
  ["bungee outline", "display"],
  ["bungee shade", "display"],
  ["bungee spice", "display"],
  ["bungee tint", "display"],
  ["butcherman", "display"],
  ["butterfly kids", "handwriting"],
  ["bytesized", "sans-serif"],
  ["cabin", "sans-serif"],
  ["cabin condensed", "sans-serif"],
  ["cabin sketch", "display"],
  ["cactus classical serif", "serif"],
  ["caesar dressing", "display"],
  ["cagliostro", "sans-serif"],
  ["cairo", "sans-serif"],
  ["cairo play", "sans-serif"],
  ["cal sans", "sans-serif"],
  ["caladea", "serif"],
  ["calistoga", "display"],
  ["calligraffitti", "handwriting"],
  ["cambay", "sans-serif"],
  ["cambo", "serif"],
  ["candal", "sans-serif"],
  ["cantarell", "sans-serif"],
  ["cantata one", "serif"],
  ["cantora one", "sans-serif"],
  ["caprasimo", "display"],
  ["capriola", "sans-serif"],
  ["caramel", "handwriting"],
  ["carattere", "handwriting"],
  ["cardo", "serif"],
  ["carlito", "sans-serif"],
  ["carme", "sans-serif"],
  ["carrois gothic", "sans-serif"],
  ["carrois gothic sc", "sans-serif"],
  ["carter one", "display"],
  ["cascadia code", "sans-serif"],
  ["cascadia mono", "sans-serif"],
  ["castoro", "serif"],
  ["castoro titling", "display"],
  ["catamaran", "sans-serif"],
  ["caudex", "serif"],
  ["cause", "handwriting"],
  ["caveat", "handwriting"],
  ["caveat brush", "handwriting"],
  ["cedarville cursive", "handwriting"],
  ["ceviche one", "display"],
  ["chakra petch", "sans-serif"],
  ["changa", "sans-serif"],
  ["changa one", "display"],
  ["chango", "display"],
  ["charis sil", "serif"],
  ["charm", "handwriting"],
  ["charmonman", "handwriting"],
  ["chathura", "sans-serif"],
  ["chau philomene one", "sans-serif"],
  ["chela one", "display"],
  ["chelsea market", "display"],
  ["chenla", "display"],
  ["cherish", "handwriting"],
  ["cherry bomb one", "display"],
  ["cherry cream soda", "display"],
  ["cherry swash", "display"],
  ["chewy", "display"],
  ["chicle", "display"],
  ["chilanka", "handwriting"],
  ["chiron goround tc", "sans-serif"],
  ["chiron hei hk", "sans-serif"],
  ["chiron sung hk", "serif"],
  ["chivo", "sans-serif"],
  ["chivo mono", "monospace"],
  ["chocolate classical sans", "sans-serif"],
  ["chokokutai", "display"],
  ["chonburi", "display"],
  ["cinzel", "serif"],
  ["cinzel decorative", "display"],
  ["clicker script", "handwriting"],
  ["climate crisis", "display"],
  ["coda", "display"],
  ["codystar", "display"],
  ["coiny", "display"],
  ["combo", "display"],
  ["comfortaa", "display"],
  ["comforter", "handwriting"],
  ["comforter brush", "handwriting"],
  ["comic neue", "handwriting"],
  ["comic relief", "display"],
  ["coming soon", "handwriting"],
  ["comme", "sans-serif"],
  ["commissioner", "sans-serif"],
  ["concert one", "display"],
  ["condiment", "handwriting"],
  ["content", "display"],
  ["contrail one", "display"],
  ["convergence", "sans-serif"],
  ["cookie", "handwriting"],
  ["copse", "serif"],
  ["coral pixels", "display"],
  ["corben", "display"],
  ["corinthia", "handwriting"],
  ["cormorant", "serif"],
  ["cormorant garamond", "serif"],
  ["cormorant infant", "serif"],
  ["cormorant sc", "serif"],
  ["cormorant unicase", "serif"],
  ["cormorant upright", "serif"],
  ["cossette texte", "sans-serif"],
  ["cossette titre", "sans-serif"],
  ["courgette", "handwriting"],
  ["courier prime", "monospace"],
  ["cousine", "monospace"],
  ["coustard", "serif"],
  ["covered by your grace", "handwriting"],
  ["crafty girls", "handwriting"],
  ["creepster", "display"],
  ["crete round", "serif"],
  ["crimson pro", "serif"],
  ["crimson text", "serif"],
  ["croissant one", "display"],
  ["crushed", "display"],
  ["cuprum", "sans-serif"],
  ["cute font", "display"],
  ["cutive", "serif"],
  ["cutive mono", "monospace"],
  ["dm mono", "monospace"],
  ["dm sans", "sans-serif"],
  ["dm serif display", "serif"],
  ["dm serif text", "serif"],
  ["dai banna sil", "serif"],
  ["damion", "handwriting"],
  ["dancing script", "handwriting"],
  ["danfo", "serif"],
  ["dangrek", "display"],
  ["darker grotesque", "sans-serif"],
  ["darumadrop one", "display"],
  ["david libre", "serif"],
  ["dawning of a new day", "handwriting"],
  ["days one", "sans-serif"],
  ["dekko", "handwriting"],
  ["dela gothic one", "display"],
  ["delicious handrawn", "handwriting"],
  ["delius", "handwriting"],
  ["delius swash caps", "handwriting"],
  ["delius unicase", "handwriting"],
  ["della respira", "serif"],
  ["denk one", "sans-serif"],
  ["devonshire", "handwriting"],
  ["dhurjati", "sans-serif"],
  ["didact gothic", "sans-serif"],
  ["diphylleia", "serif"],
  ["diplomata", "display"],
  ["diplomata sc", "display"],
  ["do hyeon", "sans-serif"],
  ["dokdo", "display"],
  ["domine", "serif"],
  ["donegal one", "serif"],
  ["dongle", "sans-serif"],
  ["doppio one", "sans-serif"],
  ["dorsa", "sans-serif"],
  ["dosis", "sans-serif"],
  ["dotgothic16", "sans-serif"],
  ["doto", "sans-serif"],
  ["dr sugiyama", "handwriting"],
  ["duru sans", "sans-serif"],
  ["dynapuff", "display"],
  ["dynalight", "display"],
  ["eb garamond", "serif"],
  ["eagle lake", "handwriting"],
  ["east sea dokdo", "handwriting"],
  ["eater", "display"],
  ["economica", "sans-serif"],
  ["eczar", "serif"],
  ["edu au vic wa nt arrows", "handwriting"],
  ["edu au vic wa nt dots", "handwriting"],
  ["edu au vic wa nt guides", "handwriting"],
  ["edu au vic wa nt hand", "handwriting"],
  ["edu au vic wa nt pre", "handwriting"],
  ["edu nsw act cursive", "handwriting"],
  ["edu nsw act foundation", "handwriting"],
  ["edu nsw act hand pre", "handwriting"],
  ["edu qld beginner", "handwriting"],
  ["edu qld hand", "handwriting"],
  ["edu sa beginner", "handwriting"],
  ["edu sa hand", "handwriting"],
  ["edu tas beginner", "handwriting"],
  ["edu vic wa nt beginner", "handwriting"],
  ["edu vic wa nt hand", "handwriting"],
  ["edu vic wa nt hand pre", "handwriting"],
  ["el messiri", "sans-serif"],
  ["electrolize", "sans-serif"],
  ["elms sans", "sans-serif"],
  ["elsie", "display"],
  ["elsie swash caps", "display"],
  ["emblema one", "display"],
  ["emilys candy", "display"],
  ["encode sans", "sans-serif"],
  ["encode sans condensed", "sans-serif"],
  ["encode sans expanded", "sans-serif"],
  ["encode sans sc", "sans-serif"],
  ["encode sans semi condensed", "sans-serif"],
  ["encode sans semi expanded", "sans-serif"],
  ["engagement", "handwriting"],
  ["englebert", "sans-serif"],
  ["enriqueta", "serif"],
  ["ephesis", "handwriting"],
  ["epilogue", "sans-serif"],
  ["epunda sans", "sans-serif"],
  ["epunda slab", "serif"],
  ["erica one", "display"],
  ["esteban", "serif"],
  ["estonia", "handwriting"],
  ["euphoria script", "handwriting"],
  ["ewert", "display"],
  ["exile", "display"],
  ["exo", "sans-serif"],
  ["exo 2", "sans-serif"],
  ["expletus sans", "display"],
  ["explora", "handwriting"],
  ["faculty glyphic", "sans-serif"],
  ["fahkwang", "sans-serif"],
  ["familjen grotesk", "sans-serif"],
  ["fanwood text", "serif"],
  ["farro", "sans-serif"],
  ["farsan", "display"],
  ["fascinate", "display"],
  ["fascinate inline", "display"],
  ["faster one", "display"],
  ["fasthand", "display"],
  ["fauna one", "serif"],
  ["faustina", "serif"],
  ["federant", "display"],
  ["federo", "sans-serif"],
  ["felipa", "handwriting"],
  ["fenix", "serif"],
  ["festive", "handwriting"],
  ["figtree", "sans-serif"],
  ["finger paint", "display"],
  ["finlandica", "sans-serif"],
  ["fira code", "monospace"],
  ["fira mono", "monospace"],
  ["fira sans", "sans-serif"],
  ["fira sans condensed", "sans-serif"],
  ["fira sans extra condensed", "sans-serif"],
  ["fjalla one", "sans-serif"],
  ["fjord one", "serif"],
  ["flamenco", "display"],
  ["flavors", "display"],
  ["fleur de leah", "handwriting"],
  ["flow block", "display"],
  ["flow circular", "display"],
  ["flow rounded", "display"],
  ["foldit", "display"],
  ["fondamento", "handwriting"],
  ["fontdiner swanky", "display"],
  ["forum", "display"],
  ["fragment mono", "monospace"],
  ["francois one", "sans-serif"],
  ["frank ruhl libre", "serif"],
  ["fraunces", "serif"],
  ["freckle face", "display"],
  ["fredericka the great", "display"],
  ["fredoka", "sans-serif"],
  ["freehand", "display"],
  ["freeman", "display"],
  ["fresca", "sans-serif"],
  ["frijole", "display"],
  ["fruktur", "display"],
  ["fugaz one", "display"],
  ["fuggles", "handwriting"],
  ["funnel display", "display"],
  ["funnel sans", "sans-serif"],
  ["fustat", "sans-serif"],
  ["fuzzy bubbles", "handwriting"],
  ["gfs didot", "serif"],
  ["gfs neohellenic", "sans-serif"],
  ["ga maamli", "display"],
  ["gabarito", "display"],
  ["gabriela", "serif"],
  ["gaegu", "handwriting"],
  ["gafata", "sans-serif"],
  ["gajraj one", "display"],
  ["galada", "display"],
  ["galdeano", "sans-serif"],
  ["galindo", "display"],
  ["gamja flower", "handwriting"],
  ["gantari", "sans-serif"],
  ["gasoek one", "sans-serif"],
  ["gayathri", "sans-serif"],
  ["geist", "sans-serif"],
  ["geist mono", "monospace"],
  ["gelasio", "serif"],
  ["gemunu libre", "sans-serif"],
  ["genos", "sans-serif"],
  ["gentium book plus", "serif"],
  ["gentium plus", "serif"],
  ["geo", "sans-serif"],
  ["geologica", "sans-serif"],
  ["geom", "sans-serif"],
  ["georama", "sans-serif"],
  ["geostar", "display"],
  ["geostar fill", "display"],
  ["germania one", "display"],
  ["gideon roman", "display"],
  ["gidole", "sans-serif"],
  ["gidugu", "sans-serif"],
  ["gilda display", "serif"],
  ["girassol", "display"],
  ["give you glory", "handwriting"],
  ["glass antiqua", "display"],
  ["glegoo", "serif"],
  ["gloock", "serif"],
  ["gloria hallelujah", "handwriting"],
  ["glory", "sans-serif"],
  ["gluten", "display"],
  ["goblin one", "display"],
  ["gochi hand", "handwriting"],
  ["goldman", "display"],
  ["golos text", "sans-serif"],
  ["google sans", "sans-serif"],
  ["google sans code", "monospace"],
  ["google sans flex", "sans-serif"],
  ["gorditas", "display"],
  ["gothic a1", "sans-serif"],
  ["gotu", "sans-serif"],
  ["goudy bookletter 1911", "serif"],
  ["gowun batang", "serif"],
  ["gowun dodum", "sans-serif"],
  ["graduate", "serif"],
  ["grand hotel", "handwriting"],
  ["grandiflora one", "serif"],
  ["grandstander", "display"],
  ["grape nuts", "handwriting"],
  ["gravitas one", "display"],
  ["great vibes", "handwriting"],
  ["grechen fuemen", "handwriting"],
  ["grenze", "serif"],
  ["grenze gotisch", "display"],
  ["grey qo", "handwriting"],
  ["griffy", "display"],
  ["gruppo", "sans-serif"],
  ["gudea", "sans-serif"],
  ["gugi", "display"],
  ["gulzar", "serif"],
  ["gupter", "serif"],
  ["gurajada", "sans-serif"],
  ["gwendolyn", "handwriting"],
  ["habibi", "serif"],
  ["hachi maru pop", "handwriting"],
  ["hahmlet", "serif"],
  ["halant", "serif"],
  ["hammersmith one", "sans-serif"],
  ["hanalei", "display"],
  ["hanalei fill", "display"],
  ["handjet", "display"],
  ["handlee", "handwriting"],
  ["hanken grotesk", "sans-serif"],
  ["hanuman", "serif"],
  ["happy monkey", "display"],
  ["harmattan", "sans-serif"],
  ["headland one", "serif"],
  ["hedvig letters sans", "sans-serif"],
  ["hedvig letters serif", "serif"],
  ["heebo", "sans-serif"],
  ["henny penny", "display"],
  ["hepta slab", "serif"],
  ["herr von muellerhoff", "handwriting"],
  ["hi melody", "handwriting"],
  ["hina mincho", "serif"],
  ["hind", "sans-serif"],
  ["hind guntur", "sans-serif"],
  ["hind madurai", "sans-serif"],
  ["hind mysuru", "sans-serif"],
  ["hind siliguri", "sans-serif"],
  ["hind vadodara", "sans-serif"],
  ["holtwood one sc", "serif"],
  ["homemade apple", "handwriting"],
  ["homenaje", "sans-serif"],
  ["honk", "display"],
  ["host grotesk", "sans-serif"],
  ["hubballi", "sans-serif"],
  ["hubot sans", "sans-serif"],
  ["huninn", "sans-serif"],
  ["hurricane", "handwriting"],
  ["ibm plex mono", "monospace"],
  ["ibm plex sans", "sans-serif"],
  ["ibm plex sans arabic", "sans-serif"],
  ["ibm plex sans condensed", "sans-serif"],
  ["ibm plex sans devanagari", "sans-serif"],
  ["ibm plex sans hebrew", "sans-serif"],
  ["ibm plex sans jp", "sans-serif"],
  ["ibm plex sans kr", "sans-serif"],
  ["ibm plex sans thai", "sans-serif"],
  ["ibm plex sans thai looped", "sans-serif"],
  ["ibm plex serif", "serif"],
  ["im fell dw pica", "serif"],
  ["im fell dw pica sc", "serif"],
  ["im fell double pica", "serif"],
  ["im fell double pica sc", "serif"],
  ["im fell english", "serif"],
  ["im fell english sc", "serif"],
  ["im fell french canon", "serif"],
  ["im fell french canon sc", "serif"],
  ["im fell great primer", "serif"],
  ["im fell great primer sc", "serif"],
  ["iansui", "handwriting"],
  ["ibarra real nova", "serif"],
  ["iceberg", "display"],
  ["iceland", "display"],
  ["imbue", "serif"],
  ["imperial script", "handwriting"],
  ["imprima", "sans-serif"],
  ["inclusive sans", "sans-serif"],
  ["inconsolata", "monospace"],
  ["inder", "sans-serif"],
  ["indie flower", "handwriting"],
  ["ingrid darling", "handwriting"],
  ["inika", "serif"],
  ["inknut antiqua", "serif"],
  ["inria sans", "sans-serif"],
  ["inria serif", "serif"],
  ["inspiration", "handwriting"],
  ["instrument sans", "sans-serif"],
  ["instrument serif", "serif"],
  ["intel one mono", "monospace"],
  ["inter", "sans-serif"],
  ["inter tight", "sans-serif"],
  ["irish grover", "display"],
  ["island moments", "handwriting"],
  ["istok web", "sans-serif"],
  ["italiana", "sans-serif"],
  ["italianno", "handwriting"],
  ["itim", "handwriting"],
  ["jacquard 12", "display"],
  ["jacquard 12 charted", "display"],
  ["jacquard 24", "display"],
  ["jacquard 24 charted", "display"],
  ["jacquarda bastarda 9", "display"],
  ["jacquarda bastarda 9 charted", "display"],
  ["jacques francois", "serif"],
  ["jacques francois shadow", "display"],
  ["jaini", "display"],
  ["jaini purva", "display"],
  ["jaldi", "sans-serif"],
  ["jaro", "sans-serif"],
  ["jersey 10", "display"],
  ["jersey 10 charted", "display"],
  ["jersey 15", "display"],
  ["jersey 15 charted", "display"],
  ["jersey 20", "display"],
  ["jersey 20 charted", "display"],
  ["jersey 25", "display"],
  ["jersey 25 charted", "display"],
  ["jetbrains mono", "monospace"],
  ["jim nightshade", "handwriting"],
  ["joan", "serif"],
  ["jockey one", "sans-serif"],
  ["jolly lodger", "display"],
  ["jomhuria", "display"],
  ["jomolhari", "serif"],
  ["josefin sans", "sans-serif"],
  ["josefin slab", "serif"],
  ["jost", "sans-serif"],
  ["joti one", "display"],
  ["jua", "sans-serif"],
  ["judson", "serif"],
  ["julee", "handwriting"],
  ["julius sans one", "sans-serif"],
  ["junge", "serif"],
  ["jura", "sans-serif"],
  ["just another hand", "handwriting"],
  ["just me again down here", "handwriting"],
  ["k2d", "sans-serif"],
  ["kablammo", "display"],
  ["kadwa", "serif"],
  ["kaisei decol", "serif"],
  ["kaisei harunoumi", "serif"],
  ["kaisei opti", "serif"],
  ["kaisei tokumin", "serif"],
  ["kalam", "handwriting"],
  ["kalnia", "serif"],
  ["kalnia glaze", "display"],
  ["kameron", "serif"],
  ["kanchenjunga", "sans-serif"],
  ["kanit", "sans-serif"],
  ["kantumruy pro", "sans-serif"],
  ["kapakana", "handwriting"],
  ["karantina", "display"],
  ["karla", "sans-serif"],
  ["karla tamil inclined", "sans-serif"],
  ["karla tamil upright", "sans-serif"],
  ["karma", "serif"],
  ["katibeh", "display"],
  ["kaushan script", "handwriting"],
  ["kavivanar", "handwriting"],
  ["kavoon", "display"],
  ["kay pho du", "serif"],
  ["kdam thmor pro", "sans-serif"],
  ["keania one", "display"],
  ["kedebideri", "sans-serif"],
  ["kelly slab", "display"],
  ["kenia", "display"],
  ["khand", "sans-serif"],
  ["khmer", "sans-serif"],
  ["khula", "sans-serif"],
  ["kings", "handwriting"],
  ["kirang haerang", "display"],
  ["kite one", "sans-serif"],
  ["kiwi maru", "serif"],
  ["klee one", "handwriting"],
  ["knewave", "display"],
  ["koho", "sans-serif"],
  ["kodchasan", "sans-serif"],
  ["kode mono", "monospace"],
  ["koh santepheap", "serif"],
  ["kolker brush", "handwriting"],
  ["konkhmer sleokchher", "display"],
  ["kosugi", "sans-serif"],
  ["kosugi maru", "sans-serif"],
  ["kotta one", "serif"],
  ["koulen", "display"],
  ["kranky", "display"],
  ["kreon", "serif"],
  ["kristi", "handwriting"],
  ["krona one", "sans-serif"],
  ["krub", "sans-serif"],
  ["kufam", "sans-serif"],
  ["kulim park", "sans-serif"],
  ["kumar one", "display"],
  ["kumar one outline", "display"],
  ["kumbh sans", "sans-serif"],
  ["kurale", "serif"],
  ["line seed jp", "sans-serif"],
  ["lxgw marker gothic", "sans-serif"],
  ["lxgw wenkai mono tc", "monospace"],
  ["lxgw wenkai tc", "handwriting"],
  ["la belle aurore", "handwriting"],
  ["labrada", "serif"],
  ["lacquer", "display"],
  ["laila", "serif"],
  ["lakki reddy", "handwriting"],
  ["lalezar", "sans-serif"],
  ["lancelot", "display"],
  ["langar", "display"],
  ["lateef", "serif"],
  ["lato", "sans-serif"],
  ["lavishly yours", "handwriting"],
  ["league gothic", "sans-serif"],
  ["league script", "handwriting"],
  ["league spartan", "sans-serif"],
  ["leckerli one", "handwriting"],
  ["ledger", "serif"],
  ["lekton", "monospace"],
  ["lemon", "display"],
  ["lemonada", "display"],
  ["lexend", "sans-serif"],
  ["lexend deca", "sans-serif"],
  ["lexend exa", "sans-serif"],
  ["lexend giga", "sans-serif"],
  ["lexend mega", "sans-serif"],
  ["lexend peta", "sans-serif"],
  ["lexend tera", "sans-serif"],
  ["lexend zetta", "sans-serif"],
  ["libertinus keyboard", "display"],
  ["libertinus math", "display"],
  ["libertinus mono", "monospace"],
  ["libertinus sans", "sans-serif"],
  ["libertinus serif", "serif"],
  ["libertinus serif display", "display"],
  ["libre barcode 128", "display"],
  ["libre barcode 128 text", "display"],
  ["libre barcode 39", "display"],
  ["libre barcode 39 extended", "display"],
  ["libre barcode 39 extended text", "display"],
  ["libre barcode 39 text", "display"],
  ["libre barcode ean13 text", "display"],
  ["libre baskerville", "serif"],
  ["libre bodoni", "serif"],
  ["libre caslon display", "serif"],
  ["libre caslon text", "serif"],
  ["libre franklin", "sans-serif"],
  ["licorice", "handwriting"],
  ["life savers", "display"],
  ["lilex", "monospace"],
  ["lilita one", "display"],
  ["lily script one", "display"],
  ["limelight", "display"],
  ["linden hill", "serif"],
  ["linefont", "display"],
  ["lisu bosa", "serif"],
  ["liter", "sans-serif"],
  ["literata", "serif"],
  ["liu jian mao cao", "handwriting"],
  ["livvic", "sans-serif"],
  ["lobster", "display"],
  ["lobster two", "display"],
  ["londrina outline", "display"],
  ["londrina shadow", "display"],
  ["londrina sketch", "display"],
  ["londrina solid", "display"],
  ["long cang", "handwriting"],
  ["lora", "serif"],
  ["love light", "handwriting"],
  ["love ya like a sister", "display"],
  ["loved by the king", "handwriting"],
  ["lovers quarrel", "handwriting"],
  ["luckiest guy", "display"],
  ["lugrasimo", "handwriting"],
  ["lumanosimo", "handwriting"],
  ["lunasima", "sans-serif"],
  ["lusitana", "serif"],
  ["lustria", "serif"],
  ["luxurious roman", "display"],
  ["luxurious script", "handwriting"],
  ["m plus 1", "sans-serif"],
  ["m plus 1 code", "monospace"],
  ["m plus 1p", "sans-serif"],
  ["m plus 2", "sans-serif"],
  ["m plus code latin", "sans-serif"],
  ["m plus rounded 1c", "sans-serif"],
  ["ma shan zheng", "handwriting"],
  ["macondo", "display"],
  ["macondo swash caps", "display"],
  ["mada", "sans-serif"],
  ["madimi one", "sans-serif"],
  ["magra", "sans-serif"],
  ["maiden orange", "serif"],
  ["maitree", "serif"],
  ["major mono display", "monospace"],
  ["mako", "sans-serif"],
  ["mali", "handwriting"],
  ["mallanna", "sans-serif"],
  ["maname", "serif"],
  ["mandali", "sans-serif"],
  ["manjari", "sans-serif"],
  ["manrope", "sans-serif"],
  ["mansalva", "handwriting"],
  ["manuale", "serif"],
  ["manufacturing consent", "display"],
  ["marcellus", "serif"],
  ["marcellus sc", "serif"],
  ["marck script", "handwriting"],
  ["margarine", "display"],
  ["marhey", "display"],
  ["markazi text", "serif"],
  ["marko one", "serif"],
  ["marmelad", "sans-serif"],
  ["martel", "serif"],
  ["martel sans", "sans-serif"],
  ["martian mono", "monospace"],
  ["marvel", "sans-serif"],
  ["matangi", "sans-serif"],
  ["mate", "serif"],
  ["mate sc", "serif"],
  ["matemasie", "sans-serif"],
  ["maven pro", "sans-serif"],
  ["mclaren", "display"],
  ["mea culpa", "handwriting"],
  ["meddon", "handwriting"],
  ["medievalsharp", "display"],
  ["medula one", "display"],
  ["meera inimai", "sans-serif"],
  ["megrim", "display"],
  ["meie script", "handwriting"],
  ["menbere", "sans-serif"],
  ["meow script", "handwriting"],
  ["merienda", "handwriting"],
  ["merriweather", "serif"],
  ["merriweather sans", "sans-serif"],
  ["metal", "display"],
  ["metal mania", "display"],
  ["metamorphous", "display"],
  ["metrophobic", "sans-serif"],
  ["michroma", "sans-serif"],
  ["micro 5", "display"],
  ["micro 5 charted", "display"],
  ["milonga", "display"],
  ["miltonian", "display"],
  ["miltonian tattoo", "display"],
  ["mina", "sans-serif"],
  ["mingzat", "sans-serif"],
  ["miniver", "display"],
  ["miriam libre", "sans-serif"],
  ["mirza", "serif"],
  ["miss fajardose", "handwriting"],
  ["mitr", "sans-serif"],
  ["mochiy pop one", "sans-serif"],
  ["mochiy pop p one", "sans-serif"],
  ["modak", "display"],
  ["modern antiqua", "display"],
  ["moderustic", "sans-serif"],
  ["mogra", "display"],
  ["mohave", "sans-serif"],
  ["moirai one", "display"],
  ["molengo", "sans-serif"],
  ["molle", "handwriting"],
  ["momo signature", "sans-serif"],
  ["momo trust display", "sans-serif"],
  ["momo trust sans", "sans-serif"],
  ["mona sans", "sans-serif"],
  ["monda", "sans-serif"],
  ["monofett", "monospace"],
  ["monomakh", "display"],
  ["monomaniac one", "sans-serif"],
  ["monoton", "display"],
  ["monsieur la doulaise", "handwriting"],
  ["montaga", "serif"],
  ["montagu slab", "serif"],
  ["montecarlo", "handwriting"],
  ["montez", "handwriting"],
  ["montserrat", "sans-serif"],
  ["montserrat alternates", "sans-serif"],
  ["montserrat underline", "sans-serif"],
  ["moo lah lah", "display"],
  ["mooli", "sans-serif"],
  ["moon dance", "handwriting"],
  ["moul", "display"],
  ["moulpali", "sans-serif"],
  ["mountains of christmas", "display"],
  ["mouse memoirs", "sans-serif"],
  ["mozilla headline", "sans-serif"],
  ["mozilla text", "sans-serif"],
  ["mr bedfort", "handwriting"],
  ["mr dafoe", "handwriting"],
  ["mr de haviland", "handwriting"],
  ["mrs saint delafield", "handwriting"],
  ["mrs sheppards", "handwriting"],
  ["ms madi", "handwriting"],
  ["mukta", "sans-serif"],
  ["mukta mahee", "sans-serif"],
  ["mukta malar", "sans-serif"],
  ["mukta vaani", "sans-serif"],
  ["mulish", "sans-serif"],
  ["murecho", "sans-serif"],
  ["museomoderno", "display"],
  ["my soul", "handwriting"],
  ["mynerve", "handwriting"],
  ["mystery quest", "display"],
  ["ntr", "sans-serif"],
  ["nabla", "display"],
  ["namdhinggo", "serif"],
  ["nanum brush script", "handwriting"],
  ["nanum gothic", "sans-serif"],
  ["nanum gothic coding", "handwriting"],
  ["nanum myeongjo", "serif"],
  ["nanum pen script", "handwriting"],
  ["narnoor", "sans-serif"],
  ["nata sans", "sans-serif"],
  ["national park", "sans-serif"],
  ["neonderthaw", "handwriting"],
  ["nerko one", "handwriting"],
  ["neucha", "handwriting"],
  ["neuton", "serif"],
  ["new amsterdam", "sans-serif"],
  ["new rocker", "display"],
  ["new tegomin", "serif"],
  ["news cycle", "sans-serif"],
  ["newsreader", "serif"],
  ["niconne", "handwriting"],
  ["niramit", "sans-serif"],
  ["nixie one", "display"],
  ["nobile", "sans-serif"],
  ["nokora", "sans-serif"],
  ["norican", "handwriting"],
  ["nosifer", "display"],
  ["notable", "sans-serif"],
  ["nothing you could do", "handwriting"],
  ["noticia text", "serif"],
  ["noto color emoji", "sans-serif"],
  ["noto emoji", "sans-serif"],
  ["noto kufi arabic", "sans-serif"],
  ["noto music", "sans-serif"],
  ["noto naskh arabic", "serif"],
  ["noto nastaliq urdu", "serif"],
  ["noto rashi hebrew", "serif"],
  ["noto sans", "sans-serif"],
  ["noto sans adlam", "sans-serif"],
  ["noto sans adlam unjoined", "sans-serif"],
  ["noto sans anatolian hieroglyphs", "sans-serif"],
  ["noto sans arabic", "sans-serif"],
  ["noto sans armenian", "sans-serif"],
  ["noto sans avestan", "sans-serif"],
  ["noto sans balinese", "sans-serif"],
  ["noto sans bamum", "sans-serif"],
  ["noto sans bassa vah", "sans-serif"],
  ["noto sans batak", "sans-serif"],
  ["noto sans bengali", "sans-serif"],
  ["noto sans bhaiksuki", "sans-serif"],
  ["noto sans brahmi", "sans-serif"],
  ["noto sans buginese", "sans-serif"],
  ["noto sans buhid", "sans-serif"],
  ["noto sans canadian aboriginal", "sans-serif"],
  ["noto sans carian", "sans-serif"],
  ["noto sans caucasian albanian", "sans-serif"],
  ["noto sans chakma", "sans-serif"],
  ["noto sans cham", "sans-serif"],
  ["noto sans cherokee", "sans-serif"],
  ["noto sans chorasmian", "sans-serif"],
  ["noto sans coptic", "sans-serif"],
  ["noto sans cuneiform", "sans-serif"],
  ["noto sans cypriot", "sans-serif"],
  ["noto sans cypro minoan", "sans-serif"],
  ["noto sans deseret", "sans-serif"],
  ["noto sans devanagari", "sans-serif"],
  ["noto sans display", "sans-serif"],
  ["noto sans duployan", "sans-serif"],
  ["noto sans egyptian hieroglyphs", "sans-serif"],
  ["noto sans elbasan", "sans-serif"],
  ["noto sans elymaic", "sans-serif"],
  ["noto sans ethiopic", "sans-serif"],
  ["noto sans georgian", "sans-serif"],
  ["noto sans glagolitic", "sans-serif"],
  ["noto sans gothic", "sans-serif"],
  ["noto sans grantha", "sans-serif"],
  ["noto sans gujarati", "sans-serif"],
  ["noto sans gunjala gondi", "sans-serif"],
  ["noto sans gurmukhi", "sans-serif"],
  ["noto sans hk", "sans-serif"],
  ["noto sans hanifi rohingya", "sans-serif"],
  ["noto sans hanunoo", "sans-serif"],
  ["noto sans hatran", "sans-serif"],
  ["noto sans hebrew", "sans-serif"],
  ["noto sans imperial aramaic", "sans-serif"],
  ["noto sans indic siyaq numbers", "sans-serif"],
  ["noto sans inscriptional pahlavi", "sans-serif"],
  ["noto sans inscriptional parthian", "sans-serif"],
  ["noto sans jp", "sans-serif"],
  ["noto sans javanese", "sans-serif"],
  ["noto sans kr", "sans-serif"],
  ["noto sans kaithi", "sans-serif"],
  ["noto sans kannada", "sans-serif"],
  ["noto sans kawi", "sans-serif"],
  ["noto sans kayah li", "sans-serif"],
  ["noto sans kharoshthi", "sans-serif"],
  ["noto sans khmer", "sans-serif"],
  ["noto sans khojki", "sans-serif"],
  ["noto sans khudawadi", "sans-serif"],
  ["noto sans lao", "sans-serif"],
  ["noto sans lao looped", "sans-serif"],
  ["noto sans lepcha", "sans-serif"],
  ["noto sans limbu", "sans-serif"],
  ["noto sans linear a", "sans-serif"],
  ["noto sans linear b", "sans-serif"],
  ["noto sans lisu", "sans-serif"],
  ["noto sans lycian", "sans-serif"],
  ["noto sans lydian", "sans-serif"],
  ["noto sans mahajani", "sans-serif"],
  ["noto sans malayalam", "sans-serif"],
  ["noto sans mandaic", "sans-serif"],
  ["noto sans manichaean", "sans-serif"],
  ["noto sans marchen", "sans-serif"],
  ["noto sans masaram gondi", "sans-serif"],
  ["noto sans math", "sans-serif"],
  ["noto sans mayan numerals", "sans-serif"],
  ["noto sans medefaidrin", "sans-serif"],
  ["noto sans meetei mayek", "sans-serif"],
  ["noto sans mende kikakui", "sans-serif"],
  ["noto sans meroitic", "sans-serif"],
  ["noto sans miao", "sans-serif"],
  ["noto sans modi", "sans-serif"],
  ["noto sans mongolian", "sans-serif"],
  ["noto sans mono", "sans-serif"],
  ["noto sans mro", "sans-serif"],
  ["noto sans multani", "sans-serif"],
  ["noto sans myanmar", "sans-serif"],
  ["noto sans nko", "sans-serif"],
  ["noto sans nko unjoined", "sans-serif"],
  ["noto sans nabataean", "sans-serif"],
  ["noto sans nag mundari", "sans-serif"],
  ["noto sans nandinagari", "sans-serif"],
  ["noto sans new tai lue", "sans-serif"],
  ["noto sans newa", "sans-serif"],
  ["noto sans nushu", "sans-serif"],
  ["noto sans ogham", "sans-serif"],
  ["noto sans ol chiki", "sans-serif"],
  ["noto sans old hungarian", "sans-serif"],
  ["noto sans old italic", "sans-serif"],
  ["noto sans old north arabian", "sans-serif"],
  ["noto sans old permic", "sans-serif"],
  ["noto sans old persian", "sans-serif"],
  ["noto sans old sogdian", "sans-serif"],
  ["noto sans old south arabian", "sans-serif"],
  ["noto sans old turkic", "sans-serif"],
  ["noto sans oriya", "sans-serif"],
  ["noto sans osage", "sans-serif"],
  ["noto sans osmanya", "sans-serif"],
  ["noto sans pahawh hmong", "sans-serif"],
  ["noto sans palmyrene", "sans-serif"],
  ["noto sans pau cin hau", "sans-serif"],
  ["noto sans phagspa", "sans-serif"],
  ["noto sans phoenician", "sans-serif"],
  ["noto sans psalter pahlavi", "sans-serif"],
  ["noto sans rejang", "sans-serif"],
  ["noto sans runic", "sans-serif"],
  ["noto sans sc", "sans-serif"],
  ["noto sans samaritan", "sans-serif"],
  ["noto sans saurashtra", "sans-serif"],
  ["noto sans sharada", "sans-serif"],
  ["noto sans shavian", "sans-serif"],
  ["noto sans siddham", "sans-serif"],
  ["noto sans signwriting", "sans-serif"],
  ["noto sans sinhala", "sans-serif"],
  ["noto sans sogdian", "sans-serif"],
  ["noto sans sora sompeng", "sans-serif"],
  ["noto sans soyombo", "sans-serif"],
  ["noto sans sundanese", "sans-serif"],
  ["noto sans sunuwar", "sans-serif"],
  ["noto sans syloti nagri", "sans-serif"],
  ["noto sans symbols", "sans-serif"],
  ["noto sans symbols 2", "sans-serif"],
  ["noto sans syriac", "sans-serif"],
  ["noto sans syriac eastern", "sans-serif"],
  ["noto sans syriac western", "sans-serif"],
  ["noto sans tc", "sans-serif"],
  ["noto sans tagalog", "sans-serif"],
  ["noto sans tagbanwa", "sans-serif"],
  ["noto sans tai le", "sans-serif"],
  ["noto sans tai tham", "sans-serif"],
  ["noto sans tai viet", "sans-serif"],
  ["noto sans takri", "sans-serif"],
  ["noto sans tamil", "sans-serif"],
  ["noto sans tamil supplement", "sans-serif"],
  ["noto sans tangsa", "sans-serif"],
  ["noto sans telugu", "sans-serif"],
  ["noto sans thaana", "sans-serif"],
  ["noto sans thai", "sans-serif"],
  ["noto sans thai looped", "sans-serif"],
  ["noto sans tifinagh", "sans-serif"],
  ["noto sans tirhuta", "sans-serif"],
  ["noto sans ugaritic", "sans-serif"],
  ["noto sans vai", "sans-serif"],
  ["noto sans vithkuqi", "sans-serif"],
  ["noto sans wancho", "sans-serif"],
  ["noto sans warang citi", "sans-serif"],
  ["noto sans yi", "sans-serif"],
  ["noto sans zanabazar square", "sans-serif"],
  ["noto serif", "serif"],
  ["noto serif ahom", "serif"],
  ["noto serif armenian", "serif"],
  ["noto serif balinese", "serif"],
  ["noto serif bengali", "serif"],
  ["noto serif devanagari", "serif"],
  ["noto serif display", "serif"],
  ["noto serif dives akuru", "serif"],
  ["noto serif dogra", "serif"],
  ["noto serif ethiopic", "serif"],
  ["noto serif georgian", "serif"],
  ["noto serif grantha", "serif"],
  ["noto serif gujarati", "serif"],
  ["noto serif gurmukhi", "serif"],
  ["noto serif hk", "serif"],
  ["noto serif hebrew", "serif"],
  ["noto serif hentaigana", "serif"],
  ["noto serif jp", "serif"],
  ["noto serif kr", "serif"],
  ["noto serif kannada", "serif"],
  ["noto serif khitan small script", "serif"],
  ["noto serif khmer", "serif"],
  ["noto serif khojki", "serif"],
  ["noto serif lao", "serif"],
  ["noto serif makasar", "serif"],
  ["noto serif malayalam", "serif"],
  ["noto serif myanmar", "serif"],
  ["noto serif np hmong", "serif"],
  ["noto serif old uyghur", "serif"],
  ["noto serif oriya", "serif"],
  ["noto serif ottoman siyaq", "serif"],
  ["noto serif sc", "serif"],
  ["noto serif sinhala", "serif"],
  ["noto serif tc", "serif"],
  ["noto serif tamil", "serif"],
  ["noto serif tangut", "serif"],
  ["noto serif telugu", "serif"],
  ["noto serif thai", "serif"],
  ["noto serif tibetan", "serif"],
  ["noto serif todhri", "serif"],
  ["noto serif toto", "serif"],
  ["noto serif vithkuqi", "serif"],
  ["noto serif yezidi", "serif"],
  ["noto traditional nushu", "sans-serif"],
  ["noto znamenny musical notation", "sans-serif"],
  ["nova cut", "display"],
  ["nova flat", "display"],
  ["nova mono", "monospace"],
  ["nova oval", "display"],
  ["nova round", "display"],
  ["nova script", "display"],
  ["nova slim", "display"],
  ["nova square", "display"],
  ["numans", "sans-serif"],
  ["nunito", "sans-serif"],
  ["nunito sans", "sans-serif"],
  ["nuosu sil", "sans-serif"],
  ["odibee sans", "display"],
  ["odor mean chey", "serif"],
  ["offside", "display"],
  ["oi", "display"],
  ["ojuju", "sans-serif"],
  ["old standard tt", "serif"],
  ["oldenburg", "display"],
  ["ole", "handwriting"],
  ["oleo script", "display"],
  ["oleo script swash caps", "display"],
  ["onest", "sans-serif"],
  ["oooh baby", "handwriting"],
  ["open sans", "sans-serif"],
  ["oranienbaum", "serif"],
  ["orbit", "sans-serif"],
  ["orbitron", "sans-serif"],
  ["oregano", "display"],
  ["orelega one", "display"],
  ["orienta", "sans-serif"],
  ["original surfer", "display"],
  ["oswald", "sans-serif"],
  ["outfit", "sans-serif"],
  ["over the rainbow", "handwriting"],
  ["overlock", "display"],
  ["overlock sc", "display"],
  ["overpass", "sans-serif"],
  ["overpass mono", "monospace"],
  ["ovo", "serif"],
  ["oxanium", "display"],
  ["oxygen", "sans-serif"],
  ["oxygen mono", "monospace"],
  ["pt mono", "monospace"],
  ["pt sans", "sans-serif"],
  ["pt sans caption", "sans-serif"],
  ["pt sans narrow", "sans-serif"],
  ["pt serif", "serif"],
  ["pt serif caption", "serif"],
  ["pacifico", "handwriting"],
  ["padauk", "sans-serif"],
  ["padyakke expanded one", "serif"],
  ["palanquin", "sans-serif"],
  ["palanquin dark", "sans-serif"],
  ["palette mosaic", "display"],
  ["pangolin", "handwriting"],
  ["paprika", "display"],
  ["parastoo", "serif"],
  ["parisienne", "handwriting"],
  ["parkinsans", "sans-serif"],
  ["passero one", "display"],
  ["passion one", "display"],
  ["passions conflict", "handwriting"],
  ["pathway extreme", "sans-serif"],
  ["pathway gothic one", "sans-serif"],
  ["patrick hand", "handwriting"],
  ["patrick hand sc", "handwriting"],
  ["pattaya", "sans-serif"],
  ["patua one", "display"],
  ["pavanam", "sans-serif"],
  ["paytone one", "sans-serif"],
  ["peddana", "serif"],
  ["peralta", "serif"],
  ["permanent marker", "handwriting"],
  ["petemoss", "handwriting"],
  ["petit formal script", "handwriting"],
  ["petrona", "serif"],
  ["phetsarath", "sans-serif"],
  ["philosopher", "sans-serif"],
  ["phudu", "display"],
  ["piazzolla", "serif"],
  ["piedra", "display"],
  ["pinyon script", "handwriting"],
  ["pirata one", "display"],
  ["pixelify sans", "display"],
  ["plaster", "display"],
  ["platypi", "serif"],
  ["play", "sans-serif"],
  ["playball", "display"],
  ["playfair", "serif"],
  ["playfair display", "serif"],
  ["playfair display sc", "serif"],
  ["playpen sans", "handwriting"],
  ["playpen sans arabic", "handwriting"],
  ["playpen sans deva", "handwriting"],
  ["playpen sans hebrew", "handwriting"],
  ["playpen sans thai", "handwriting"],
  ["playwrite ar", "handwriting"],
  ["playwrite ar guides", "handwriting"],
  ["playwrite at", "handwriting"],
  ["playwrite at guides", "handwriting"],
  ["playwrite au nsw", "handwriting"],
  ["playwrite au nsw guides", "handwriting"],
  ["playwrite au qld", "handwriting"],
  ["playwrite au qld guides", "handwriting"],
  ["playwrite au sa", "handwriting"],
  ["playwrite au sa guides", "handwriting"],
  ["playwrite au tas", "handwriting"],
  ["playwrite au tas guides", "handwriting"],
  ["playwrite au vic", "handwriting"],
  ["playwrite au vic guides", "handwriting"],
  ["playwrite be vlg", "handwriting"],
  ["playwrite be vlg guides", "handwriting"],
  ["playwrite be wal", "handwriting"],
  ["playwrite be wal guides", "handwriting"],
  ["playwrite br", "handwriting"],
  ["playwrite br guides", "handwriting"],
  ["playwrite ca", "handwriting"],
  ["playwrite ca guides", "handwriting"],
  ["playwrite cl", "handwriting"],
  ["playwrite cl guides", "handwriting"],
  ["playwrite co", "handwriting"],
  ["playwrite co guides", "handwriting"],
  ["playwrite cu", "handwriting"],
  ["playwrite cu guides", "handwriting"],
  ["playwrite cz", "handwriting"],
  ["playwrite cz guides", "handwriting"],
  ["playwrite de grund", "handwriting"],
  ["playwrite de grund guides", "handwriting"],
  ["playwrite de la", "handwriting"],
  ["playwrite de la guides", "handwriting"],
  ["playwrite de sas", "handwriting"],
  ["playwrite de sas guides", "handwriting"],
  ["playwrite de va", "handwriting"],
  ["playwrite de va guides", "handwriting"],
  ["playwrite dk loopet", "handwriting"],
  ["playwrite dk loopet guides", "handwriting"],
  ["playwrite dk uloopet", "handwriting"],
  ["playwrite dk uloopet guides", "handwriting"],
  ["playwrite es", "handwriting"],
  ["playwrite es deco", "handwriting"],
  ["playwrite es deco guides", "handwriting"],
  ["playwrite es guides", "handwriting"],
  ["playwrite fr moderne", "handwriting"],
  ["playwrite fr moderne guides", "handwriting"],
  ["playwrite fr trad", "handwriting"],
  ["playwrite fr trad guides", "handwriting"],
  ["playwrite gb j", "handwriting"],
  ["playwrite gb j guides", "handwriting"],
  ["playwrite gb s", "handwriting"],
  ["playwrite gb s guides", "handwriting"],
  ["playwrite hr", "handwriting"],
  ["playwrite hr guides", "handwriting"],
  ["playwrite hr lijeva", "handwriting"],
  ["playwrite hr lijeva guides", "handwriting"],
  ["playwrite hu", "handwriting"],
  ["playwrite hu guides", "handwriting"],
  ["playwrite id", "handwriting"],
  ["playwrite id guides", "handwriting"],
  ["playwrite ie", "handwriting"],
  ["playwrite ie guides", "handwriting"],
  ["playwrite in", "handwriting"],
  ["playwrite in guides", "handwriting"],
  ["playwrite is", "handwriting"],
  ["playwrite is guides", "handwriting"],
  ["playwrite it moderna", "handwriting"],
  ["playwrite it moderna guides", "handwriting"],
  ["playwrite it trad", "handwriting"],
  ["playwrite it trad guides", "handwriting"],
  ["playwrite mx", "handwriting"],
  ["playwrite mx guides", "handwriting"],
  ["playwrite ng modern", "handwriting"],
  ["playwrite ng modern guides", "handwriting"],
  ["playwrite nl", "handwriting"],
  ["playwrite nl guides", "handwriting"],
  ["playwrite no", "handwriting"],
  ["playwrite no guides", "handwriting"],
  ["playwrite nz", "handwriting"],
  ["playwrite nz basic", "handwriting"],
  ["playwrite nz basic guides", "handwriting"],
  ["playwrite nz guides", "handwriting"],
  ["playwrite pe", "handwriting"],
  ["playwrite pe guides", "handwriting"],
  ["playwrite pl", "handwriting"],
  ["playwrite pl guides", "handwriting"],
  ["playwrite pt", "handwriting"],
  ["playwrite pt guides", "handwriting"],
  ["playwrite ro", "handwriting"],
  ["playwrite ro guides", "handwriting"],
  ["playwrite sk", "handwriting"],
  ["playwrite sk guides", "handwriting"],
  ["playwrite tz", "handwriting"],
  ["playwrite tz guides", "handwriting"],
  ["playwrite us modern", "handwriting"],
  ["playwrite us modern guides", "handwriting"],
  ["playwrite us trad", "handwriting"],
  ["playwrite us trad guides", "handwriting"],
  ["playwrite vn", "handwriting"],
  ["playwrite vn guides", "handwriting"],
  ["playwrite za", "handwriting"],
  ["playwrite za guides", "handwriting"],
  ["plus jakarta sans", "sans-serif"],
  ["pochaevsk", "display"],
  ["podkova", "serif"],
  ["poetsen one", "display"],
  ["poiret one", "display"],
  ["poller one", "display"],
  ["poltawski nowy", "serif"],
  ["poly", "serif"],
  ["pompiere", "display"],
  ["ponnala", "display"],
  ["ponomar", "display"],
  ["pontano sans", "sans-serif"],
  ["poor story", "display"],
  ["poppins", "sans-serif"],
  ["port lligat sans", "sans-serif"],
  ["port lligat slab", "serif"],
  ["potta one", "display"],
  ["pragati narrow", "sans-serif"],
  ["praise", "handwriting"],
  ["prata", "serif"],
  ["preahvihear", "sans-serif"],
  ["press start 2p", "display"],
  ["pridi", "serif"],
  ["princess sofia", "handwriting"],
  ["prociono", "serif"],
  ["prompt", "sans-serif"],
  ["prosto one", "display"],
  ["protest guerrilla", "display"],
  ["protest revolution", "display"],
  ["protest riot", "display"],
  ["protest strike", "display"],
  ["proza libre", "sans-serif"],
  ["public sans", "sans-serif"],
  ["puppies play", "handwriting"],
  ["puritan", "sans-serif"],
  ["purple purse", "display"],
  ["qahiri", "sans-serif"],
  ["quando", "serif"],
  ["quantico", "sans-serif"],
  ["quattrocento", "serif"],
  ["quattrocento sans", "sans-serif"],
  ["questrial", "sans-serif"],
  ["quicksand", "sans-serif"],
  ["quintessential", "handwriting"],
  ["qwigley", "handwriting"],
  ["qwitcher grypen", "handwriting"],
  ["rem", "sans-serif"],
  ["racing sans one", "display"],
  ["radio canada", "sans-serif"],
  ["radio canada big", "sans-serif"],
  ["radley", "serif"],
  ["rajdhani", "sans-serif"],
  ["rakkas", "display"],
  ["raleway", "sans-serif"],
  ["raleway dots", "display"],
  ["ramabhadra", "sans-serif"],
  ["ramaraja", "serif"],
  ["rambla", "sans-serif"],
  ["rammetto one", "display"],
  ["rampart one", "display"],
  ["ranchers", "display"],
  ["rancho", "handwriting"],
  ["ranga", "display"],
  ["rasa", "serif"],
  ["rationale", "sans-serif"],
  ["ravi prakash", "display"],
  ["readex pro", "sans-serif"],
  ["recursive", "sans-serif"],
  ["red hat display", "sans-serif"],
  ["red hat mono", "monospace"],
  ["red hat text", "sans-serif"],
  ["red rose", "display"],
  ["redacted", "display"],
  ["redacted script", "display"],
  ["reddit mono", "monospace"],
  ["reddit sans", "sans-serif"],
  ["reddit sans condensed", "sans-serif"],
  ["redressed", "handwriting"],
  ["reem kufi", "sans-serif"],
  ["reem kufi fun", "sans-serif"],
  ["reem kufi ink", "sans-serif"],
  ["reenie beanie", "handwriting"],
  ["reggae one", "display"],
  ["rethink sans", "sans-serif"],
  ["revalia", "display"],
  ["rhodium libre", "serif"],
  ["ribeye", "display"],
  ["ribeye marrow", "display"],
  ["righteous", "display"],
  ["risque", "display"],
  ["road rage", "display"],
  ["roboto", "sans-serif"],
  ["roboto condensed", "sans-serif"],
  ["roboto flex", "sans-serif"],
  ["roboto mono", "monospace"],
  ["roboto serif", "serif"],
  ["roboto slab", "serif"],
  ["rochester", "handwriting"],
  ["rock 3d", "display"],
  ["rock salt", "handwriting"],
  ["rocknroll one", "sans-serif"],
  ["rokkitt", "serif"],
  ["romanesco", "handwriting"],
  ["ropa sans", "sans-serif"],
  ["rosario", "sans-serif"],
  ["rosarivo", "serif"],
  ["rouge script", "handwriting"],
  ["rowdies", "display"],
  ["rozha one", "serif"],
  ["rubik", "sans-serif"],
  ["rubik 80s fade", "display"],
  ["rubik beastly", "display"],
  ["rubik broken fax", "display"],
  ["rubik bubbles", "display"],
  ["rubik burned", "display"],
  ["rubik dirt", "display"],
  ["rubik distressed", "display"],
  ["rubik doodle shadow", "display"],
  ["rubik doodle triangles", "display"],
  ["rubik gemstones", "display"],
  ["rubik glitch", "display"],
  ["rubik glitch pop", "display"],
  ["rubik iso", "display"],
  ["rubik lines", "display"],
  ["rubik maps", "display"],
  ["rubik marker hatch", "display"],
  ["rubik maze", "display"],
  ["rubik microbe", "display"],
  ["rubik mono one", "sans-serif"],
  ["rubik moonrocks", "display"],
  ["rubik pixels", "display"],
  ["rubik puddles", "display"],
  ["rubik scribble", "display"],
  ["rubik spray paint", "display"],
  ["rubik storm", "display"],
  ["rubik vinyl", "display"],
  ["rubik wet paint", "display"],
  ["ruda", "sans-serif"],
  ["rufina", "serif"],
  ["ruge boogie", "handwriting"],
  ["ruluko", "sans-serif"],
  ["rum raisin", "sans-serif"],
  ["ruslan display", "display"],
  ["russo one", "sans-serif"],
  ["ruthie", "handwriting"],
  ["ruwudu", "serif"],
  ["rye", "display"],
  ["sn pro", "sans-serif"],
  ["stix two text", "serif"],
  ["suse", "sans-serif"],
  ["suse mono", "sans-serif"],
  ["sacramento", "handwriting"],
  ["sahitya", "serif"],
  ["sail", "display"],
  ["saira", "sans-serif"],
  ["saira condensed", "sans-serif"],
  ["saira extra condensed", "sans-serif"],
  ["saira semi condensed", "sans-serif"],
  ["saira stencil one", "display"],
  ["salsa", "display"],
  ["sanchez", "serif"],
  ["sancreek", "display"],
  ["sankofa display", "sans-serif"],
  ["sansation", "sans-serif"],
  ["sansita", "sans-serif"],
  ["sansita swashed", "display"],
  ["sarabun", "sans-serif"],
  ["sarala", "sans-serif"],
  ["sarina", "display"],
  ["sarpanch", "sans-serif"],
  ["sassy frass", "handwriting"],
  ["satisfy", "handwriting"],
  ["savate", "sans-serif"],
  ["sawarabi gothic", "sans-serif"],
  ["sawarabi mincho", "serif"],
  ["scada", "sans-serif"],
  ["scheherazade new", "serif"],
  ["schibsted grotesk", "sans-serif"],
  ["schoolbell", "handwriting"],
  ["science gothic", "sans-serif"],
  ["scope one", "serif"],
  ["seaweed script", "display"],
  ["secular one", "sans-serif"],
  ["sedan", "serif"],
  ["sedan sc", "serif"],
  ["sedgwick ave", "handwriting"],
  ["sedgwick ave display", "handwriting"],
  ["sekuya", "display"],
  ["sen", "sans-serif"],
  ["send flowers", "handwriting"],
  ["sevillana", "display"],
  ["seymour one", "sans-serif"],
  ["shadows into light", "handwriting"],
  ["shadows into light two", "handwriting"],
  ["shafarik", "display"],
  ["shalimar", "handwriting"],
  ["shantell sans", "display"],
  ["shanti", "sans-serif"],
  ["share", "sans-serif"],
  ["share tech", "sans-serif"],
  ["share tech mono", "monospace"],
  ["shippori antique", "sans-serif"],
  ["shippori antique b1", "sans-serif"],
  ["shippori mincho", "serif"],
  ["shippori mincho b1", "serif"],
  ["shizuru", "display"],
  ["shojumaru", "display"],
  ["short stack", "handwriting"],
  ["shrikhand", "display"],
  ["siemreap", "sans-serif"],
  ["sigmar", "display"],
  ["sigmar one", "display"],
  ["signika", "sans-serif"],
  ["signika negative", "sans-serif"],
  ["silkscreen", "display"],
  ["simonetta", "display"],
  ["single day", "display"],
  ["sintony", "sans-serif"],
  ["sirin stencil", "display"],
  ["sirivennela", "sans-serif"],
  ["six caps", "sans-serif"],
  ["sixtyfour", "monospace"],
  ["sixtyfour convergence", "monospace"],
  ["skranji", "display"],
  ["slabo 13px", "serif"],
  ["slabo 27px", "serif"],
  ["slackey", "display"],
  ["slackside one", "handwriting"],
  ["smokum", "display"],
  ["smooch", "handwriting"],
  ["smooch sans", "sans-serif"],
  ["smythe", "display"],
  ["sniglet", "display"],
  ["snippet", "sans-serif"],
  ["snowburst one", "display"],
  ["sofadi one", "display"],
  ["sofia", "handwriting"],
  ["sofia sans", "sans-serif"],
  ["sofia sans condensed", "sans-serif"],
  ["sofia sans extra condensed", "sans-serif"],
  ["sofia sans semi condensed", "sans-serif"],
  ["solitreo", "handwriting"],
  ["solway", "serif"],
  ["sometype mono", "monospace"],
  ["song myung", "serif"],
  ["sono", "sans-serif"],
  ["sonsie one", "display"],
  ["sora", "sans-serif"],
  ["sorts mill goudy", "serif"],
  ["sour gummy", "sans-serif"],
  ["source code pro", "monospace"],
  ["source sans 3", "sans-serif"],
  ["source serif 4", "serif"],
  ["space grotesk", "sans-serif"],
  ["space mono", "monospace"],
  ["special elite", "display"],
  ["special gothic", "sans-serif"],
  ["special gothic condensed one", "sans-serif"],
  ["special gothic expanded one", "sans-serif"],
  ["spectral", "serif"],
  ["spectral sc", "serif"],
  ["spicy rice", "display"],
  ["spinnaker", "sans-serif"],
  ["spirax", "display"],
  ["splash", "handwriting"],
  ["spline sans", "sans-serif"],
  ["spline sans mono", "monospace"],
  ["squada one", "display"],
  ["square peg", "handwriting"],
  ["sree krushnadevaraya", "serif"],
  ["sriracha", "handwriting"],
  ["srisakdi", "display"],
  ["staatliches", "display"],
  ["stack sans headline", "sans-serif"],
  ["stack sans notch", "sans-serif"],
  ["stack sans text", "sans-serif"],
  ["stalemate", "handwriting"],
  ["stalinist one", "display"],
  ["stardos stencil", "display"],
  ["stick", "sans-serif"],
  ["stick no bills", "sans-serif"],
  ["stint ultra condensed", "serif"],
  ["stint ultra expanded", "serif"],
  ["stoke", "serif"],
  ["story script", "sans-serif"],
  ["strait", "sans-serif"],
  ["style script", "handwriting"],
  ["stylish", "sans-serif"],
  ["sue ellen francisco", "handwriting"],
  ["suez one", "serif"],
  ["sulphur point", "sans-serif"],
  ["sumana", "serif"],
  ["sunflower", "sans-serif"],
  ["sunshiney", "handwriting"],
  ["supermercado one", "display"],
  ["sura", "serif"],
  ["suranna", "serif"],
  ["suravaram", "serif"],
  ["suwannaphum", "serif"],
  ["swanky and moo moo", "handwriting"],
  ["syncopate", "sans-serif"],
  ["syne", "sans-serif"],
  ["syne mono", "monospace"],
  ["syne tactile", "display"],
  ["tasa explorer", "sans-serif"],
  ["tasa orbiter", "sans-serif"],
  ["tac one", "sans-serif"],
  ["tagesschrift", "display"],
  ["tai heritage pro", "serif"],
  ["tajawal", "sans-serif"],
  ["tangerine", "handwriting"],
  ["tapestry", "handwriting"],
  ["taprom", "display"],
  ["tauri", "sans-serif"],
  ["taviraj", "serif"],
  ["teachers", "sans-serif"],
  ["teko", "sans-serif"],
  ["tektur", "display"],
  ["telex", "sans-serif"],
  ["tenali ramakrishna", "sans-serif"],
  ["tenor sans", "sans-serif"],
  ["text me one", "sans-serif"],
  ["texturina", "serif"],
  ["thasadith", "sans-serif"],
  ["the girl next door", "handwriting"],
  ["the nautigal", "handwriting"],
  ["tienne", "serif"],
  ["tiktok sans", "sans-serif"],
  ["tillana", "display"],
  ["tilt neon", "display"],
  ["tilt prism", "display"],
  ["tilt warp", "display"],
  ["timmana", "sans-serif"],
  ["tinos", "serif"],
  ["tiny5", "sans-serif"],
  ["tiro bangla", "serif"],
  ["tiro devanagari hindi", "serif"],
  ["tiro devanagari marathi", "serif"],
  ["tiro devanagari sanskrit", "serif"],
  ["tiro gurmukhi", "serif"],
  ["tiro kannada", "serif"],
  ["tiro tamil", "serif"],
  ["tiro telugu", "serif"],
  ["tirra", "sans-serif"],
  ["titan one", "display"],
  ["titillium web", "sans-serif"],
  ["tomorrow", "sans-serif"],
  ["tourney", "display"],
  ["trade winds", "display"],
  ["train one", "display"],
  ["triodion", "display"],
  ["trirong", "serif"],
  ["trispace", "sans-serif"],
  ["trocchi", "serif"],
  ["trochut", "display"],
  ["truculenta", "sans-serif"],
  ["trykker", "serif"],
  ["tsukimi rounded", "sans-serif"],
  ["tuffy", "sans-serif"],
  ["tulpen one", "display"],
  ["turret road", "display"],
  ["twinkle star", "handwriting"],
  ["ubuntu", "sans-serif"],
  ["ubuntu condensed", "sans-serif"],
  ["ubuntu mono", "monospace"],
  ["ubuntu sans", "sans-serif"],
  ["ubuntu sans mono", "monospace"],
  ["uchen", "serif"],
  ["ultra", "serif"],
  ["unbounded", "sans-serif"],
  ["uncial antiqua", "display"],
  ["underdog", "display"],
  ["unica one", "display"],
  ["unifrakturcook", "display"],
  ["unifrakturmaguntia", "display"],
  ["unkempt", "display"],
  ["unlock", "display"],
  ["unna", "serif"],
  ["uoqmunthenkhung", "serif"],
  ["updock", "handwriting"],
  ["urbanist", "sans-serif"],
  ["vt323", "monospace"],
  ["vampiro one", "display"],
  ["varela", "sans-serif"],
  ["varela round", "sans-serif"],
  ["varta", "sans-serif"],
  ["vast shadow", "serif"],
  ["vazirmatn", "sans-serif"],
  ["vend sans", "sans-serif"],
  ["vesper libre", "serif"],
  ["viaoda libre", "display"],
  ["vibes", "display"],
  ["vibur", "handwriting"],
  ["victor mono", "monospace"],
  ["vidaloka", "serif"],
  ["viga", "sans-serif"],
  ["vina sans", "display"],
  ["voces", "sans-serif"],
  ["volkhov", "serif"],
  ["vollkorn", "serif"],
  ["vollkorn sc", "serif"],
  ["voltaire", "sans-serif"],
  ["vujahday script", "handwriting"],
  ["wdxl lubrifont jp n", "sans-serif"],
  ["wdxl lubrifont sc", "sans-serif"],
  ["wdxl lubrifont tc", "sans-serif"],
  ["waiting for the sunrise", "handwriting"],
  ["wallpoet", "display"],
  ["walter turncoat", "handwriting"],
  ["warnes", "display"],
  ["water brush", "handwriting"],
  ["waterfall", "handwriting"],
  ["wavefont", "display"],
  ["wellfleet", "serif"],
  ["wendy one", "sans-serif"],
  ["whisper", "handwriting"],
  ["windsong", "handwriting"],
  ["winky rough", "sans-serif"],
  ["winky sans", "sans-serif"],
  ["wire one", "sans-serif"],
  ["wittgenstein", "serif"],
  ["wix madefor display", "sans-serif"],
  ["wix madefor text", "sans-serif"],
  ["work sans", "sans-serif"],
  ["workbench", "monospace"],
  ["xanh mono", "monospace"],
  ["yaldevi", "sans-serif"],
  ["yanone kaffeesatz", "sans-serif"],
  ["yantramanav", "sans-serif"],
  ["yarndings 12", "display"],
  ["yarndings 12 charted", "display"],
  ["yarndings 20", "display"],
  ["yarndings 20 charted", "display"],
  ["yatra one", "display"],
  ["yellowtail", "handwriting"],
  ["yeon sung", "display"],
  ["yeseva one", "display"],
  ["yesteryear", "handwriting"],
  ["yomogi", "handwriting"],
  ["young serif", "serif"],
  ["yrsa", "serif"],
  ["ysabeau", "sans-serif"],
  ["ysabeau infant", "sans-serif"],
  ["ysabeau office", "sans-serif"],
  ["ysabeau sc", "sans-serif"],
  ["yuji boku", "serif"],
  ["yuji hentaigana akari", "handwriting"],
  ["yuji hentaigana akebono", "handwriting"],
  ["yuji mai", "serif"],
  ["yuji syuku", "serif"],
  ["yusei magic", "sans-serif"],
  ["zcool kuaile", "sans-serif"],
  ["zcool qingke huangyou", "sans-serif"],
  ["zcool xiaowei", "sans-serif"],
  ["zain", "sans-serif"],
  ["zalando sans", "sans-serif"],
  ["zalando sans expanded", "sans-serif"],
  ["zalando sans semiexpanded", "sans-serif"],
  ["zen antique", "serif"],
  ["zen antique soft", "serif"],
  ["zen dots", "display"],
  ["zen kaku gothic antique", "sans-serif"],
  ["zen kaku gothic new", "sans-serif"],
  ["zen kurenaido", "sans-serif"],
  ["zen loop", "display"],
  ["zen maru gothic", "sans-serif"],
  ["zen old mincho", "serif"],
  ["zen tokyo zoo", "display"],
  ["zeyada", "handwriting"],
  ["zhi mang xing", "handwriting"],
  ["zilla slab", "serif"],
  ["zilla slab highlight", "serif"],
]);

export function isGoogleFont(name: string): boolean {
  return GOOGLE_FONTS.has(name.toLowerCase().trim());
}

export function getGoogleFontCategory(name: string): string | null {
  return GOOGLE_FONTS.get(name.toLowerCase().trim()) ?? null;
}

export function getGoogleFontsUrl(name: string, weights?: string[]): string {
  const encoded = name.replace(/\s+/g, "+");
  const weightParam = weights && weights.length > 0
    ? ":wght@" + weights.join(";")
    : "";
  return `https://fonts.googleapis.com/css2?family=${encoded}${weightParam}&display=swap`;
}

