const SYSTEM_FONTS = new Set([
  // CSS generic families
  "serif",
  "sans-serif",
  "monospace",
  "cursive",
  "fantasy",
  "system-ui",
  "ui-serif",
  "ui-sans-serif",
  "ui-monospace",
  "ui-rounded",
  "emoji",
  "math",
  "fangsong",
  // Windows
  "arial",
  "helvetica",
  "helvetica neue",
  "times",
  "times new roman",
  "courier",
  "courier new",
  "georgia",
  "verdana",
  "tahoma",
  "trebuchet ms",
  "lucida sans",
  "lucida console",
  "lucida grande",
  "lucida sans unicode",
  "impact",
  "comic sans ms",
  "segoe ui",
  "segoe ui emoji",
  "segoe ui symbol",
  "microsoft sans serif",
  "ms gothic",
  "ms pgothic",
  "meiryo",
  "yu gothic",
  // macOS / iOS
  "-apple-system",
  "blinkmacsystemfont",
  "apple color emoji",
  "noto color emoji",
  "sf pro",
  "sf pro display",
  "sf pro text",
  "sf pro rounded",
  "sf mono",
  "sfmono-regular",
  "new york",
  "menlo",
  "monaco",
  "apple sd gothic neo",
  "pingfang sc",
  "pingfang tc",
  "hiragino sans",
  "hiragino kaku gothic pro",
  // Linux
  "liberation sans",
  "liberation serif",
  "liberation mono",
  "dejavu sans",
  "dejavu sans mono",
  "dejavu serif",
  "noto sans",
  "noto serif",
  "ubuntu",
  "cantarell",
  "droid sans",
  "droid serif",
  "roboto",
  // Monospace system fonts
  "consolas",
  "andale mono",
  "source code pro",
  // CJK
  "noto sans cjk",
  "noto serif cjk",
  "malgun gothic",
  "microsoft yahei",
  "simsun",
  "simhei",
  // CSS keywords
  "inherit",
  "initial",
  "unset",
  "revert",
]);

export function isSystemFont(name: string): boolean {
  return SYSTEM_FONTS.has(name.toLowerCase().trim().replace(/['"]/g, ""));
}
