// Auto-generated from fonts.google.com/metadata/fonts
// 1929 fonts
// Last updated: 2026-04-17T06:03:26.009Z

const GOOGLE_FONTS: Map<string, string> = new Map([
  ["abeezee", "ABeeZee|sans-serif"],
  ["abel", "Abel|sans-serif"],
  ["abhaya libre", "Abhaya Libre|serif"],
  ["aboreto", "Aboreto|display"],
  ["abril fatface", "Abril Fatface|display"],
  ["abyssinica sil", "Abyssinica SIL|serif"],
  ["aclonica", "Aclonica|sans-serif"],
  ["acme", "Acme|sans-serif"],
  ["actor", "Actor|sans-serif"],
  ["adamina", "Adamina|serif"],
  ["adlam display", "ADLaM Display|display"],
  ["advent pro", "Advent Pro|sans-serif"],
  ["afacad", "Afacad|sans-serif"],
  ["afacad flux", "Afacad Flux|sans-serif"],
  ["agbalumo", "Agbalumo|display"],
  ["agdasima", "Agdasima|sans-serif"],
  ["agu display", "Agu Display|display"],
  ["aguafina script", "Aguafina Script|handwriting"],
  ["akatab", "Akatab|sans-serif"],
  ["akaya kanadaka", "Akaya Kanadaka|display"],
  ["akaya telivigala", "Akaya Telivigala|display"],
  ["akronim", "Akronim|display"],
  ["akshar", "Akshar|sans-serif"],
  ["aladin", "Aladin|display"],
  ["alan sans", "Alan Sans|sans-serif"],
  ["alata", "Alata|sans-serif"],
  ["alatsi", "Alatsi|sans-serif"],
  ["albert sans", "Albert Sans|sans-serif"],
  ["aldrich", "Aldrich|sans-serif"],
  ["alef", "Alef|sans-serif"],
  ["alegreya", "Alegreya|serif"],
  ["alegreya sans", "Alegreya Sans|sans-serif"],
  ["alegreya sans sc", "Alegreya Sans SC|sans-serif"],
  ["alegreya sc", "Alegreya SC|serif"],
  ["aleo", "Aleo|serif"],
  ["alex brush", "Alex Brush|handwriting"],
  ["alexandria", "Alexandria|sans-serif"],
  ["alfa slab one", "Alfa Slab One|display"],
  ["alice", "Alice|serif"],
  ["alike", "Alike|serif"],
  ["alike angular", "Alike Angular|serif"],
  ["alkalami", "Alkalami|serif"],
  ["alkatra", "Alkatra|display"],
  ["allan", "Allan|display"],
  ["allerta", "Allerta|sans-serif"],
  ["allerta stencil", "Allerta Stencil|sans-serif"],
  ["allison", "Allison|handwriting"],
  ["allkin", "Allkin|display"],
  ["allura", "Allura|handwriting"],
  ["almarai", "Almarai|sans-serif"],
  ["almendra", "Almendra|serif"],
  ["almendra display", "Almendra Display|display"],
  ["almendra sc", "Almendra SC|serif"],
  ["alumni sans", "Alumni Sans|sans-serif"],
  ["alumni sans collegiate one", "Alumni Sans Collegiate One|sans-serif"],
  ["alumni sans inline one", "Alumni Sans Inline One|display"],
  ["alumni sans pinstripe", "Alumni Sans Pinstripe|sans-serif"],
  ["alumni sans sc", "Alumni Sans SC|sans-serif"],
  ["alyamama", "Alyamama|serif"],
  ["amarante", "Amarante|display"],
  ["amaranth", "Amaranth|sans-serif"],
  ["amarna", "Amarna|sans-serif"],
  ["amatic sc", "Amatic SC|handwriting"],
  ["amethysta", "Amethysta|serif"],
  ["amiko", "Amiko|sans-serif"],
  ["amiri", "Amiri|serif"],
  ["amiri quran", "Amiri Quran|serif"],
  ["amita", "Amita|handwriting"],
  ["anaheim", "Anaheim|sans-serif"],
  ["ancizar sans", "Ancizar Sans|sans-serif"],
  ["ancizar serif", "Ancizar Serif|serif"],
  ["andada pro", "Andada Pro|serif"],
  ["andika", "Andika|sans-serif"],
  ["anek bangla", "Anek Bangla|sans-serif"],
  ["anek devanagari", "Anek Devanagari|sans-serif"],
  ["anek gujarati", "Anek Gujarati|sans-serif"],
  ["anek gurmukhi", "Anek Gurmukhi|sans-serif"],
  ["anek kannada", "Anek Kannada|sans-serif"],
  ["anek latin", "Anek Latin|sans-serif"],
  ["anek malayalam", "Anek Malayalam|sans-serif"],
  ["anek odia", "Anek Odia|sans-serif"],
  ["anek tamil", "Anek Tamil|sans-serif"],
  ["anek telugu", "Anek Telugu|sans-serif"],
  ["angkor", "Angkor|display"],
  ["annapurna sil", "Annapurna SIL|serif"],
  ["annie use your telescope", "Annie Use Your Telescope|handwriting"],
  ["anonymous pro", "Anonymous Pro|monospace"],
  ["anta", "Anta|sans-serif"],
  ["antic", "Antic|sans-serif"],
  ["antic didone", "Antic Didone|serif"],
  ["antic slab", "Antic Slab|serif"],
  ["anton", "Anton|sans-serif"],
  ["anton sc", "Anton SC|sans-serif"],
  ["antonio", "Antonio|sans-serif"],
  ["anuphan", "Anuphan|sans-serif"],
  ["anybody", "Anybody|display"],
  ["aoboshi one", "Aoboshi One|serif"],
  ["ar one sans", "AR One Sans|sans-serif"],
  ["arapey", "Arapey|serif"],
  ["arbutus", "Arbutus|serif"],
  ["arbutus slab", "Arbutus Slab|serif"],
  ["architects daughter", "Architects Daughter|handwriting"],
  ["archivo", "Archivo|sans-serif"],
  ["archivo black", "Archivo Black|sans-serif"],
  ["archivo narrow", "Archivo Narrow|sans-serif"],
  ["are you serious", "Are You Serious|handwriting"],
  ["aref ruqaa", "Aref Ruqaa|serif"],
  ["aref ruqaa ink", "Aref Ruqaa Ink|serif"],
  ["arima", "Arima|display"],
  ["arimo", "Arimo|sans-serif"],
  ["arizonia", "Arizonia|handwriting"],
  ["armata", "Armata|sans-serif"],
  ["arsenal", "Arsenal|sans-serif"],
  ["arsenal sc", "Arsenal SC|sans-serif"],
  ["artifika", "Artifika|serif"],
  ["arvo", "Arvo|serif"],
  ["arya", "Arya|sans-serif"],
  ["asap", "Asap|sans-serif"],
  ["asap condensed", "Asap Condensed|sans-serif"],
  ["asar", "Asar|serif"],
  ["asimovian", "Asimovian|sans-serif"],
  ["asset", "Asset|display"],
  ["assistant", "Assistant|sans-serif"],
  ["asta sans", "Asta Sans|sans-serif"],
  ["astloch", "Astloch|display"],
  ["asul", "Asul|serif"],
  ["athiti", "Athiti|sans-serif"],
  ["atkinson hyperlegible", "Atkinson Hyperlegible|sans-serif"],
  ["atkinson hyperlegible mono", "Atkinson Hyperlegible Mono|sans-serif"],
  ["atkinson hyperlegible next", "Atkinson Hyperlegible Next|sans-serif"],
  ["atma", "Atma|display"],
  ["atomic age", "Atomic Age|display"],
  ["aubrey", "Aubrey|display"],
  ["audiowide", "Audiowide|display"],
  ["autour one", "Autour One|display"],
  ["average", "Average|serif"],
  ["average sans", "Average Sans|sans-serif"],
  ["averia gruesa libre", "Averia Gruesa Libre|display"],
  ["averia libre", "Averia Libre|display"],
  ["averia sans libre", "Averia Sans Libre|display"],
  ["averia serif libre", "Averia Serif Libre|display"],
  ["azeret mono", "Azeret Mono|monospace"],
  ["b612", "B612|sans-serif"],
  ["b612 mono", "B612 Mono|monospace"],
  ["babylonica", "Babylonica|handwriting"],
  ["bacasime antique", "Bacasime Antique|serif"],
  ["bad script", "Bad Script|handwriting"],
  ["badeen display", "Badeen Display|display"],
  ["bagel fat one", "Bagel Fat One|display"],
  ["bahiana", "Bahiana|display"],
  ["bahianita", "Bahianita|display"],
  ["bai jamjuree", "Bai Jamjuree|sans-serif"],
  ["bakbak one", "Bakbak One|display"],
  ["ballet", "Ballet|handwriting"],
  ["baloo 2", "Baloo 2|display"],
  ["baloo bhai 2", "Baloo Bhai 2|display"],
  ["baloo bhaijaan 2", "Baloo Bhaijaan 2|display"],
  ["baloo bhaina 2", "Baloo Bhaina 2|display"],
  ["baloo chettan 2", "Baloo Chettan 2|display"],
  ["baloo da 2", "Baloo Da 2|display"],
  ["baloo paaji 2", "Baloo Paaji 2|display"],
  ["baloo tamma 2", "Baloo Tamma 2|display"],
  ["baloo tammudu 2", "Baloo Tammudu 2|display"],
  ["baloo thambi 2", "Baloo Thambi 2|display"],
  ["balsamiq sans", "Balsamiq Sans|display"],
  ["balthazar", "Balthazar|serif"],
  ["bangers", "Bangers|display"],
  ["barlow", "Barlow|sans-serif"],
  ["barlow condensed", "Barlow Condensed|sans-serif"],
  ["barlow semi condensed", "Barlow Semi Condensed|sans-serif"],
  ["barriecito", "Barriecito|display"],
  ["barrio", "Barrio|display"],
  ["basic", "Basic|sans-serif"],
  ["baskervville", "Baskervville|serif"],
  ["baskervville sc", "Baskervville SC|serif"],
  ["battambang", "Battambang|display"],
  ["baumans", "Baumans|display"],
  ["bayon", "Bayon|sans-serif"],
  ["bbh bartle", "BBH Bartle|sans-serif"],
  ["bbh bogle", "BBH Bogle|sans-serif"],
  ["bbh hegarty", "BBH Hegarty|sans-serif"],
  ["be vietnam pro", "Be Vietnam Pro|sans-serif"],
  ["beau rivage", "Beau Rivage|handwriting"],
  ["bebas neue", "Bebas Neue|sans-serif"],
  ["beiruti", "Beiruti|sans-serif"],
  ["belanosima", "Belanosima|sans-serif"],
  ["belgrano", "Belgrano|serif"],
  ["bellefair", "Bellefair|serif"],
  ["belleza", "Belleza|sans-serif"],
  ["bellota", "Bellota|display"],
  ["bellota text", "Bellota Text|display"],
  ["benchnine", "BenchNine|sans-serif"],
  ["benne", "Benne|serif"],
  ["bentham", "Bentham|serif"],
  ["berkshire swash", "Berkshire Swash|handwriting"],
  ["besley", "Besley|serif"],
  ["betania patmos", "Betania Patmos|handwriting"],
  ["betania patmos gdl", "Betania Patmos GDL|handwriting"],
  ["betania patmos in", "Betania Patmos In|handwriting"],
  ["betania patmos in gdl", "Betania Patmos In GDL|handwriting"],
  ["beth ellen", "Beth Ellen|handwriting"],
  ["bevan", "Bevan|serif"],
  ["bhutuka expanded one", "BhuTuka Expanded One|serif"],
  ["big shoulders", "Big Shoulders|display"],
  ["big shoulders inline", "Big Shoulders Inline|display"],
  ["big shoulders stencil", "Big Shoulders Stencil|display"],
  ["bigelow rules", "Bigelow Rules|display"],
  ["bigshot one", "Bigshot One|display"],
  ["bilbo", "Bilbo|handwriting"],
  ["bilbo swash caps", "Bilbo Swash Caps|handwriting"],
  ["biorhyme", "BioRhyme|serif"],
  ["biorhyme expanded", "BioRhyme Expanded|serif"],
  ["birthstone", "Birthstone|handwriting"],
  ["birthstone bounce", "Birthstone Bounce|handwriting"],
  ["biryani", "Biryani|sans-serif"],
  ["bitcount", "Bitcount|display"],
  ["bitcount grid double", "Bitcount Grid Double|display"],
  ["bitcount grid double ink", "Bitcount Grid Double Ink|display"],
  ["bitcount grid single", "Bitcount Grid Single|display"],
  ["bitcount grid single ink", "Bitcount Grid Single Ink|display"],
  ["bitcount ink", "Bitcount Ink|display"],
  ["bitcount prop double", "Bitcount Prop Double|display"],
  ["bitcount prop double ink", "Bitcount Prop Double Ink|display"],
  ["bitcount prop single", "Bitcount Prop Single|display"],
  ["bitcount prop single ink", "Bitcount Prop Single Ink|display"],
  ["bitcount single", "Bitcount Single|display"],
  ["bitcount single ink", "Bitcount Single Ink|display"],
  ["bitter", "Bitter|serif"],
  ["biz udgothic", "BIZ UDGothic|sans-serif"],
  ["biz udmincho", "BIZ UDMincho|serif"],
  ["biz udpgothic", "BIZ UDPGothic|sans-serif"],
  ["biz udpmincho", "BIZ UDPMincho|serif"],
  ["bj cree", "BJ Cree|serif"],
  ["black and white picture", "Black And White Picture|display"],
  ["black han sans", "Black Han Sans|sans-serif"],
  ["black ops one", "Black Ops One|display"],
  ["blaka", "Blaka|display"],
  ["blaka hollow", "Blaka Hollow|display"],
  ["blaka ink", "Blaka Ink|display"],
  ["blinker", "Blinker|sans-serif"],
  ["bodoni moda", "Bodoni Moda|serif"],
  ["bodoni moda sc", "Bodoni Moda SC|serif"],
  ["bokor", "Bokor|display"],
  ["boldonse", "Boldonse|display"],
  ["bona nova", "Bona Nova|serif"],
  ["bona nova sc", "Bona Nova SC|serif"],
  ["bonbon", "Bonbon|handwriting"],
  ["bonheur royale", "Bonheur Royale|handwriting"],
  ["boogaloo", "Boogaloo|display"],
  ["borel", "Borel|handwriting"],
  ["bowlby one", "Bowlby One|display"],
  ["bowlby one sc", "Bowlby One SC|display"],
  ["bpmf huninn", "Bpmf Huninn|sans-serif"],
  ["bpmf iansui", "Bpmf Iansui|handwriting"],
  ["bpmf zihi kai std", "Bpmf Zihi Kai Std|sans-serif"],
  ["braah one", "Braah One|sans-serif"],
  ["brawler", "Brawler|serif"],
  ["bree serif", "Bree Serif|serif"],
  ["bricolage grotesque", "Bricolage Grotesque|sans-serif"],
  ["bruno ace", "Bruno Ace|display"],
  ["bruno ace sc", "Bruno Ace SC|display"],
  ["brygada 1918", "Brygada 1918|serif"],
  ["bubblegum sans", "Bubblegum Sans|display"],
  ["bubbler one", "Bubbler One|sans-serif"],
  ["buda", "Buda|display"],
  ["buenard", "Buenard|serif"],
  ["bungee", "Bungee|display"],
  ["bungee hairline", "Bungee Hairline|display"],
  ["bungee inline", "Bungee Inline|display"],
  ["bungee outline", "Bungee Outline|display"],
  ["bungee shade", "Bungee Shade|display"],
  ["bungee spice", "Bungee Spice|display"],
  ["bungee tint", "Bungee Tint|display"],
  ["butcherman", "Butcherman|display"],
  ["butterfly kids", "Butterfly Kids|handwriting"],
  ["bytesized", "Bytesized|sans-serif"],
  ["cabin", "Cabin|sans-serif"],
  ["cabin condensed", "Cabin Condensed|sans-serif"],
  ["cabin sketch", "Cabin Sketch|display"],
  ["cactus classical serif", "Cactus Classical Serif|serif"],
  ["caesar dressing", "Caesar Dressing|display"],
  ["cagliostro", "Cagliostro|sans-serif"],
  ["cairo", "Cairo|sans-serif"],
  ["cairo play", "Cairo Play|sans-serif"],
  ["cal sans", "Cal Sans|sans-serif"],
  ["caladea", "Caladea|serif"],
  ["calistoga", "Calistoga|display"],
  ["calligraffitti", "Calligraffitti|handwriting"],
  ["cambay", "Cambay|sans-serif"],
  ["cambo", "Cambo|serif"],
  ["candal", "Candal|sans-serif"],
  ["cantarell", "Cantarell|sans-serif"],
  ["cantata one", "Cantata One|serif"],
  ["cantora one", "Cantora One|sans-serif"],
  ["caprasimo", "Caprasimo|display"],
  ["capriola", "Capriola|sans-serif"],
  ["caramel", "Caramel|handwriting"],
  ["carattere", "Carattere|handwriting"],
  ["cardo", "Cardo|serif"],
  ["carlito", "Carlito|sans-serif"],
  ["carme", "Carme|sans-serif"],
  ["carrois gothic", "Carrois Gothic|sans-serif"],
  ["carrois gothic sc", "Carrois Gothic SC|sans-serif"],
  ["carter one", "Carter One|display"],
  ["cascadia code", "Cascadia Code|sans-serif"],
  ["cascadia mono", "Cascadia Mono|sans-serif"],
  ["castoro", "Castoro|serif"],
  ["castoro titling", "Castoro Titling|display"],
  ["catamaran", "Catamaran|sans-serif"],
  ["caudex", "Caudex|serif"],
  ["cause", "Cause|handwriting"],
  ["caveat", "Caveat|handwriting"],
  ["caveat brush", "Caveat Brush|handwriting"],
  ["cedarville cursive", "Cedarville Cursive|handwriting"],
  ["ceviche one", "Ceviche One|display"],
  ["chakra petch", "Chakra Petch|sans-serif"],
  ["changa", "Changa|sans-serif"],
  ["changa one", "Changa One|display"],
  ["chango", "Chango|display"],
  ["charis sil", "Charis SIL|serif"],
  ["charm", "Charm|handwriting"],
  ["charmonman", "Charmonman|handwriting"],
  ["chathura", "Chathura|sans-serif"],
  ["chau philomene one", "Chau Philomene One|sans-serif"],
  ["chela one", "Chela One|display"],
  ["chelsea market", "Chelsea Market|display"],
  ["chenla", "Chenla|display"],
  ["cherish", "Cherish|handwriting"],
  ["cherry bomb one", "Cherry Bomb One|display"],
  ["cherry cream soda", "Cherry Cream Soda|display"],
  ["cherry swash", "Cherry Swash|display"],
  ["chewy", "Chewy|display"],
  ["chicle", "Chicle|display"],
  ["chilanka", "Chilanka|handwriting"],
  ["chiron goround tc", "Chiron GoRound TC|sans-serif"],
  ["chiron hei hk", "Chiron Hei HK|sans-serif"],
  ["chiron sung hk", "Chiron Sung HK|serif"],
  ["chivo", "Chivo|sans-serif"],
  ["chivo mono", "Chivo Mono|monospace"],
  ["chocolate classical sans", "Chocolate Classical Sans|sans-serif"],
  ["chokokutai", "Chokokutai|display"],
  ["chonburi", "Chonburi|display"],
  ["cinzel", "Cinzel|serif"],
  ["cinzel decorative", "Cinzel Decorative|display"],
  ["clicker script", "Clicker Script|handwriting"],
  ["climate crisis", "Climate Crisis|display"],
  ["coda", "Coda|display"],
  ["codystar", "Codystar|display"],
  ["coiny", "Coiny|display"],
  ["combo", "Combo|display"],
  ["comfortaa", "Comfortaa|display"],
  ["comforter", "Comforter|handwriting"],
  ["comforter brush", "Comforter Brush|handwriting"],
  ["comic neue", "Comic Neue|handwriting"],
  ["comic relief", "Comic Relief|display"],
  ["coming soon", "Coming Soon|handwriting"],
  ["comme", "Comme|sans-serif"],
  ["commissioner", "Commissioner|sans-serif"],
  ["concert one", "Concert One|display"],
  ["condiment", "Condiment|handwriting"],
  ["content", "Content|display"],
  ["contrail one", "Contrail One|display"],
  ["convergence", "Convergence|sans-serif"],
  ["cookie", "Cookie|handwriting"],
  ["copse", "Copse|serif"],
  ["coral pixels", "Coral Pixels|display"],
  ["corben", "Corben|display"],
  ["corinthia", "Corinthia|handwriting"],
  ["cormorant", "Cormorant|serif"],
  ["cormorant garamond", "Cormorant Garamond|serif"],
  ["cormorant infant", "Cormorant Infant|serif"],
  ["cormorant sc", "Cormorant SC|serif"],
  ["cormorant unicase", "Cormorant Unicase|serif"],
  ["cormorant upright", "Cormorant Upright|serif"],
  ["cossette texte", "Cossette Texte|sans-serif"],
  ["cossette titre", "Cossette Titre|sans-serif"],
  ["courgette", "Courgette|handwriting"],
  ["courier prime", "Courier Prime|monospace"],
  ["cousine", "Cousine|monospace"],
  ["coustard", "Coustard|serif"],
  ["covered by your grace", "Covered By Your Grace|handwriting"],
  ["crafty girls", "Crafty Girls|handwriting"],
  ["creepster", "Creepster|display"],
  ["crete round", "Crete Round|serif"],
  ["crimson pro", "Crimson Pro|serif"],
  ["crimson text", "Crimson Text|serif"],
  ["croissant one", "Croissant One|display"],
  ["crushed", "Crushed|display"],
  ["cuprum", "Cuprum|sans-serif"],
  ["cute font", "Cute Font|display"],
  ["cutive", "Cutive|serif"],
  ["cutive mono", "Cutive Mono|monospace"],
  ["dai banna sil", "Dai Banna SIL|serif"],
  ["damion", "Damion|handwriting"],
  ["dancing script", "Dancing Script|handwriting"],
  ["danfo", "Danfo|serif"],
  ["dangrek", "Dangrek|display"],
  ["darker grotesque", "Darker Grotesque|sans-serif"],
  ["darumadrop one", "Darumadrop One|display"],
  ["datatype", "Datatype|monospace"],
  ["david libre", "David Libre|serif"],
  ["dawning of a new day", "Dawning of a New Day|handwriting"],
  ["days one", "Days One|sans-serif"],
  ["dekko", "Dekko|handwriting"],
  ["dela gothic one", "Dela Gothic One|display"],
  ["delicious handrawn", "Delicious Handrawn|handwriting"],
  ["delius", "Delius|handwriting"],
  ["delius swash caps", "Delius Swash Caps|handwriting"],
  ["delius unicase", "Delius Unicase|handwriting"],
  ["della respira", "Della Respira|serif"],
  ["denk one", "Denk One|sans-serif"],
  ["devonshire", "Devonshire|handwriting"],
  ["dhurjati", "Dhurjati|sans-serif"],
  ["didact gothic", "Didact Gothic|sans-serif"],
  ["diphylleia", "Diphylleia|serif"],
  ["diplomata", "Diplomata|display"],
  ["diplomata sc", "Diplomata SC|display"],
  ["dm mono", "DM Mono|monospace"],
  ["dm sans", "DM Sans|sans-serif"],
  ["dm serif display", "DM Serif Display|serif"],
  ["dm serif text", "DM Serif Text|serif"],
  ["do hyeon", "Do Hyeon|sans-serif"],
  ["dokdo", "Dokdo|display"],
  ["domine", "Domine|serif"],
  ["donegal one", "Donegal One|serif"],
  ["dongle", "Dongle|sans-serif"],
  ["doppio one", "Doppio One|sans-serif"],
  ["dorsa", "Dorsa|sans-serif"],
  ["dosis", "Dosis|sans-serif"],
  ["dotgothic16", "DotGothic16|sans-serif"],
  ["doto", "Doto|sans-serif"],
  ["dr sugiyama", "Dr Sugiyama|handwriting"],
  ["duru sans", "Duru Sans|sans-serif"],
  ["dynalight", "Dynalight|display"],
  ["dynapuff", "DynaPuff|display"],
  ["eagle lake", "Eagle Lake|handwriting"],
  ["east sea dokdo", "East Sea Dokdo|handwriting"],
  ["eater", "Eater|display"],
  ["eb garamond", "EB Garamond|serif"],
  ["economica", "Economica|sans-serif"],
  ["eczar", "Eczar|serif"],
  ["edu au vic wa nt arrows", "Edu AU VIC WA NT Arrows|handwriting"],
  ["edu au vic wa nt dots", "Edu AU VIC WA NT Dots|handwriting"],
  ["edu au vic wa nt guides", "Edu AU VIC WA NT Guides|handwriting"],
  ["edu au vic wa nt hand", "Edu AU VIC WA NT Hand|handwriting"],
  ["edu au vic wa nt pre", "Edu AU VIC WA NT Pre|handwriting"],
  ["edu nsw act cursive", "Edu NSW ACT Cursive|handwriting"],
  ["edu nsw act foundation", "Edu NSW ACT Foundation|handwriting"],
  ["edu nsw act hand pre", "Edu NSW ACT Hand Pre|handwriting"],
  ["edu qld beginner", "Edu QLD Beginner|handwriting"],
  ["edu qld hand", "Edu QLD Hand|handwriting"],
  ["edu sa beginner", "Edu SA Beginner|handwriting"],
  ["edu sa hand", "Edu SA Hand|handwriting"],
  ["edu tas beginner", "Edu TAS Beginner|handwriting"],
  ["edu vic wa nt beginner", "Edu VIC WA NT Beginner|handwriting"],
  ["edu vic wa nt hand", "Edu VIC WA NT Hand|handwriting"],
  ["edu vic wa nt hand pre", "Edu VIC WA NT Hand Pre|handwriting"],
  ["el messiri", "El Messiri|sans-serif"],
  ["electrolize", "Electrolize|sans-serif"],
  ["elms sans", "Elms Sans|sans-serif"],
  ["elsie", "Elsie|display"],
  ["elsie swash caps", "Elsie Swash Caps|display"],
  ["emblema one", "Emblema One|display"],
  ["emilys candy", "Emilys Candy|display"],
  ["encode sans", "Encode Sans|sans-serif"],
  ["encode sans condensed", "Encode Sans Condensed|sans-serif"],
  ["encode sans expanded", "Encode Sans Expanded|sans-serif"],
  ["encode sans sc", "Encode Sans SC|sans-serif"],
  ["encode sans semi condensed", "Encode Sans Semi Condensed|sans-serif"],
  ["encode sans semi expanded", "Encode Sans Semi Expanded|sans-serif"],
  ["engagement", "Engagement|handwriting"],
  ["englebert", "Englebert|sans-serif"],
  ["enriqueta", "Enriqueta|serif"],
  ["ephesis", "Ephesis|handwriting"],
  ["epilogue", "Epilogue|sans-serif"],
  ["epunda sans", "Epunda Sans|sans-serif"],
  ["epunda slab", "Epunda Slab|serif"],
  ["erica one", "Erica One|display"],
  ["esteban", "Esteban|serif"],
  ["estonia", "Estonia|handwriting"],
  ["euphoria script", "Euphoria Script|handwriting"],
  ["ewert", "Ewert|display"],
  ["exile", "Exile|display"],
  ["exo", "Exo|sans-serif"],
  ["exo 2", "Exo 2|sans-serif"],
  ["expletus sans", "Expletus Sans|display"],
  ["explora", "Explora|handwriting"],
  ["faculty glyphic", "Faculty Glyphic|sans-serif"],
  ["fahkwang", "Fahkwang|sans-serif"],
  ["familjen grotesk", "Familjen Grotesk|sans-serif"],
  ["fanwood text", "Fanwood Text|serif"],
  ["farro", "Farro|sans-serif"],
  ["farsan", "Farsan|display"],
  ["fascinate", "Fascinate|display"],
  ["fascinate inline", "Fascinate Inline|display"],
  ["faster one", "Faster One|display"],
  ["fasthand", "Fasthand|display"],
  ["fauna one", "Fauna One|serif"],
  ["faustina", "Faustina|serif"],
  ["federant", "Federant|display"],
  ["federo", "Federo|sans-serif"],
  ["felipa", "Felipa|handwriting"],
  ["fenix", "Fenix|serif"],
  ["festive", "Festive|handwriting"],
  ["figtree", "Figtree|sans-serif"],
  ["finger paint", "Finger Paint|display"],
  ["finlandica", "Finlandica|sans-serif"],
  ["fira code", "Fira Code|monospace"],
  ["fira mono", "Fira Mono|monospace"],
  ["fira sans", "Fira Sans|sans-serif"],
  ["fira sans condensed", "Fira Sans Condensed|sans-serif"],
  ["fira sans extra condensed", "Fira Sans Extra Condensed|sans-serif"],
  ["fjalla one", "Fjalla One|sans-serif"],
  ["fjord one", "Fjord One|serif"],
  ["flamenco", "Flamenco|display"],
  ["flavors", "Flavors|display"],
  ["fleur de leah", "Fleur De Leah|handwriting"],
  ["flow block", "Flow Block|display"],
  ["flow circular", "Flow Circular|display"],
  ["flow rounded", "Flow Rounded|display"],
  ["foldit", "Foldit|display"],
  ["fondamento", "Fondamento|handwriting"],
  ["fontdiner swanky", "Fontdiner Swanky|display"],
  ["forum", "Forum|display"],
  ["fragment mono", "Fragment Mono|monospace"],
  ["francois one", "Francois One|sans-serif"],
  ["frank ruhl libre", "Frank Ruhl Libre|serif"],
  ["fraunces", "Fraunces|serif"],
  ["freckle face", "Freckle Face|display"],
  ["fredericka the great", "Fredericka the Great|display"],
  ["fredoka", "Fredoka|sans-serif"],
  ["freehand", "Freehand|display"],
  ["freeman", "Freeman|display"],
  ["fresca", "Fresca|sans-serif"],
  ["frijole", "Frijole|display"],
  ["fruktur", "Fruktur|display"],
  ["fugaz one", "Fugaz One|display"],
  ["fuggles", "Fuggles|handwriting"],
  ["funnel display", "Funnel Display|display"],
  ["funnel sans", "Funnel Sans|sans-serif"],
  ["fustat", "Fustat|sans-serif"],
  ["fuzzy bubbles", "Fuzzy Bubbles|handwriting"],
  ["ga maamli", "Ga Maamli|display"],
  ["gabarito", "Gabarito|display"],
  ["gabriela", "Gabriela|serif"],
  ["gaegu", "Gaegu|handwriting"],
  ["gafata", "Gafata|sans-serif"],
  ["gajraj one", "Gajraj One|display"],
  ["galada", "Galada|display"],
  ["galdeano", "Galdeano|sans-serif"],
  ["galindo", "Galindo|display"],
  ["gamja flower", "Gamja Flower|handwriting"],
  ["gantari", "Gantari|sans-serif"],
  ["gasoek one", "Gasoek One|sans-serif"],
  ["gayathri", "Gayathri|sans-serif"],
  ["geist", "Geist|sans-serif"],
  ["geist mono", "Geist Mono|monospace"],
  ["gelasio", "Gelasio|serif"],
  ["gemunu libre", "Gemunu Libre|sans-serif"],
  ["genos", "Genos|sans-serif"],
  ["gentium book plus", "Gentium Book Plus|serif"],
  ["gentium plus", "Gentium Plus|serif"],
  ["geo", "Geo|sans-serif"],
  ["geologica", "Geologica|sans-serif"],
  ["geom", "Geom|sans-serif"],
  ["georama", "Georama|sans-serif"],
  ["geostar", "Geostar|display"],
  ["geostar fill", "Geostar Fill|display"],
  ["germania one", "Germania One|display"],
  ["gfs didot", "GFS Didot|serif"],
  ["gfs neohellenic", "GFS Neohellenic|sans-serif"],
  ["gideon roman", "Gideon Roman|display"],
  ["gidole", "Gidole|sans-serif"],
  ["gidugu", "Gidugu|sans-serif"],
  ["gilda display", "Gilda Display|serif"],
  ["girassol", "Girassol|display"],
  ["give you glory", "Give You Glory|handwriting"],
  ["glass antiqua", "Glass Antiqua|display"],
  ["glegoo", "Glegoo|serif"],
  ["gloock", "Gloock|serif"],
  ["gloria hallelujah", "Gloria Hallelujah|handwriting"],
  ["glory", "Glory|sans-serif"],
  ["gluten", "Gluten|display"],
  ["goblin one", "Goblin One|display"],
  ["gochi hand", "Gochi Hand|handwriting"],
  ["goldman", "Goldman|display"],
  ["golos text", "Golos Text|sans-serif"],
  ["google sans", "Google Sans|sans-serif"],
  ["google sans code", "Google Sans Code|monospace"],
  ["google sans flex", "Google Sans Flex|sans-serif"],
  ["gorditas", "Gorditas|display"],
  ["gothic a1", "Gothic A1|sans-serif"],
  ["gotu", "Gotu|sans-serif"],
  ["goudy bookletter 1911", "Goudy Bookletter 1911|serif"],
  ["gowun batang", "Gowun Batang|serif"],
  ["gowun dodum", "Gowun Dodum|sans-serif"],
  ["graduate", "Graduate|serif"],
  ["grand hotel", "Grand Hotel|handwriting"],
  ["grandiflora one", "Grandiflora One|serif"],
  ["grandstander", "Grandstander|display"],
  ["grape nuts", "Grape Nuts|handwriting"],
  ["gravitas one", "Gravitas One|display"],
  ["great vibes", "Great Vibes|handwriting"],
  ["grechen fuemen", "Grechen Fuemen|handwriting"],
  ["grenze", "Grenze|serif"],
  ["grenze gotisch", "Grenze Gotisch|display"],
  ["grey qo", "Grey Qo|handwriting"],
  ["griffy", "Griffy|display"],
  ["gruppo", "Gruppo|sans-serif"],
  ["gudea", "Gudea|sans-serif"],
  ["gugi", "Gugi|display"],
  ["gulzar", "Gulzar|serif"],
  ["gupter", "Gupter|serif"],
  ["gurajada", "Gurajada|sans-serif"],
  ["gveret levin", "Gveret Levin|handwriting"],
  ["gwendolyn", "Gwendolyn|handwriting"],
  ["habibi", "Habibi|serif"],
  ["hachi maru pop", "Hachi Maru Pop|handwriting"],
  ["hahmlet", "Hahmlet|serif"],
  ["halant", "Halant|serif"],
  ["hammersmith one", "Hammersmith One|sans-serif"],
  ["hanalei", "Hanalei|display"],
  ["hanalei fill", "Hanalei Fill|display"],
  ["handjet", "Handjet|display"],
  ["handlee", "Handlee|handwriting"],
  ["hanken grotesk", "Hanken Grotesk|sans-serif"],
  ["hanuman", "Hanuman|serif"],
  ["happy monkey", "Happy Monkey|display"],
  ["harmattan", "Harmattan|sans-serif"],
  ["headland one", "Headland One|serif"],
  ["hedvig letters sans", "Hedvig Letters Sans|sans-serif"],
  ["hedvig letters serif", "Hedvig Letters Serif|serif"],
  ["heebo", "Heebo|sans-serif"],
  ["henny penny", "Henny Penny|display"],
  ["hepta slab", "Hepta Slab|serif"],
  ["herr von muellerhoff", "Herr Von Muellerhoff|handwriting"],
  ["hi melody", "Hi Melody|handwriting"],
  ["hina mincho", "Hina Mincho|serif"],
  ["hind", "Hind|sans-serif"],
  ["hind guntur", "Hind Guntur|sans-serif"],
  ["hind madurai", "Hind Madurai|sans-serif"],
  ["hind mysuru", "Hind Mysuru|sans-serif"],
  ["hind siliguri", "Hind Siliguri|sans-serif"],
  ["hind vadodara", "Hind Vadodara|sans-serif"],
  ["holtwood one sc", "Holtwood One SC|serif"],
  ["homemade apple", "Homemade Apple|handwriting"],
  ["homenaje", "Homenaje|sans-serif"],
  ["honk", "Honk|display"],
  ["host grotesk", "Host Grotesk|sans-serif"],
  ["hubballi", "Hubballi|sans-serif"],
  ["hubot sans", "Hubot Sans|sans-serif"],
  ["huninn", "Huninn|sans-serif"],
  ["hurricane", "Hurricane|handwriting"],
  ["iansui", "Iansui|handwriting"],
  ["ibarra real nova", "Ibarra Real Nova|serif"],
  ["ibm plex mono", "IBM Plex Mono|monospace"],
  ["ibm plex sans", "IBM Plex Sans|sans-serif"],
  ["ibm plex sans arabic", "IBM Plex Sans Arabic|sans-serif"],
  ["ibm plex sans condensed", "IBM Plex Sans Condensed|sans-serif"],
  ["ibm plex sans devanagari", "IBM Plex Sans Devanagari|sans-serif"],
  ["ibm plex sans hebrew", "IBM Plex Sans Hebrew|sans-serif"],
  ["ibm plex sans jp", "IBM Plex Sans JP|sans-serif"],
  ["ibm plex sans kr", "IBM Plex Sans KR|sans-serif"],
  ["ibm plex sans thai", "IBM Plex Sans Thai|sans-serif"],
  ["ibm plex sans thai looped", "IBM Plex Sans Thai Looped|sans-serif"],
  ["ibm plex serif", "IBM Plex Serif|serif"],
  ["iceberg", "Iceberg|display"],
  ["iceland", "Iceland|display"],
  ["idiqlat", "Idiqlat|serif"],
  ["im fell double pica", "IM Fell Double Pica|serif"],
  ["im fell double pica sc", "IM Fell Double Pica SC|serif"],
  ["im fell dw pica", "IM Fell DW Pica|serif"],
  ["im fell dw pica sc", "IM Fell DW Pica SC|serif"],
  ["im fell english", "IM Fell English|serif"],
  ["im fell english sc", "IM Fell English SC|serif"],
  ["im fell french canon", "IM Fell French Canon|serif"],
  ["im fell french canon sc", "IM Fell French Canon SC|serif"],
  ["im fell great primer", "IM Fell Great Primer|serif"],
  ["im fell great primer sc", "IM Fell Great Primer SC|serif"],
  ["imbue", "Imbue|serif"],
  ["imperial script", "Imperial Script|handwriting"],
  ["imprima", "Imprima|sans-serif"],
  ["inclusive sans", "Inclusive Sans|sans-serif"],
  ["inconsolata", "Inconsolata|monospace"],
  ["inder", "Inder|sans-serif"],
  ["indie flower", "Indie Flower|handwriting"],
  ["ingrid darling", "Ingrid Darling|handwriting"],
  ["inika", "Inika|serif"],
  ["inknut antiqua", "Inknut Antiqua|serif"],
  ["inria sans", "Inria Sans|sans-serif"],
  ["inria serif", "Inria Serif|serif"],
  ["inspiration", "Inspiration|handwriting"],
  ["instrument sans", "Instrument Sans|sans-serif"],
  ["instrument serif", "Instrument Serif|serif"],
  ["intel one mono", "Intel One Mono|monospace"],
  ["inter", "Inter|sans-serif"],
  ["inter tight", "Inter Tight|sans-serif"],
  ["iosevka charon", "Iosevka Charon|monospace"],
  ["iosevka charon mono", "Iosevka Charon Mono|monospace"],
  ["irish grover", "Irish Grover|display"],
  ["island moments", "Island Moments|handwriting"],
  ["istok web", "Istok Web|sans-serif"],
  ["italiana", "Italiana|sans-serif"],
  ["italianno", "Italianno|handwriting"],
  ["itim", "Itim|handwriting"],
  ["jacquard 12", "Jacquard 12|display"],
  ["jacquard 12 charted", "Jacquard 12 Charted|display"],
  ["jacquard 24", "Jacquard 24|display"],
  ["jacquard 24 charted", "Jacquard 24 Charted|display"],
  ["jacquarda bastarda 9", "Jacquarda Bastarda 9|display"],
  ["jacquarda bastarda 9 charted", "Jacquarda Bastarda 9 Charted|display"],
  ["jacques francois", "Jacques Francois|serif"],
  ["jacques francois shadow", "Jacques Francois Shadow|display"],
  ["jaini", "Jaini|display"],
  ["jaini purva", "Jaini Purva|display"],
  ["jaldi", "Jaldi|sans-serif"],
  ["jaro", "Jaro|sans-serif"],
  ["jersey 10", "Jersey 10|display"],
  ["jersey 10 charted", "Jersey 10 Charted|display"],
  ["jersey 15", "Jersey 15|display"],
  ["jersey 15 charted", "Jersey 15 Charted|display"],
  ["jersey 20", "Jersey 20|display"],
  ["jersey 20 charted", "Jersey 20 Charted|display"],
  ["jersey 25", "Jersey 25|display"],
  ["jersey 25 charted", "Jersey 25 Charted|display"],
  ["jetbrains mono", "JetBrains Mono|monospace"],
  ["jim nightshade", "Jim Nightshade|handwriting"],
  ["joan", "Joan|serif"],
  ["jockey one", "Jockey One|sans-serif"],
  ["jolly lodger", "Jolly Lodger|display"],
  ["jomhuria", "Jomhuria|display"],
  ["jomolhari", "Jomolhari|serif"],
  ["josefin sans", "Josefin Sans|sans-serif"],
  ["josefin slab", "Josefin Slab|serif"],
  ["jost", "Jost|sans-serif"],
  ["joti one", "Joti One|display"],
  ["jua", "Jua|sans-serif"],
  ["judson", "Judson|serif"],
  ["julee", "Julee|handwriting"],
  ["julius sans one", "Julius Sans One|sans-serif"],
  ["junge", "Junge|serif"],
  ["jura", "Jura|sans-serif"],
  ["just another hand", "Just Another Hand|handwriting"],
  ["just me again down here", "Just Me Again Down Here|handwriting"],
  ["k2d", "K2D|sans-serif"],
  ["kablammo", "Kablammo|display"],
  ["kadwa", "Kadwa|serif"],
  ["kaisei decol", "Kaisei Decol|serif"],
  ["kaisei harunoumi", "Kaisei HarunoUmi|serif"],
  ["kaisei opti", "Kaisei Opti|serif"],
  ["kaisei tokumin", "Kaisei Tokumin|serif"],
  ["kalam", "Kalam|handwriting"],
  ["kalnia", "Kalnia|serif"],
  ["kalnia glaze", "Kalnia Glaze|display"],
  ["kameron", "Kameron|serif"],
  ["kanchenjunga", "Kanchenjunga|sans-serif"],
  ["kanit", "Kanit|sans-serif"],
  ["kantumruy pro", "Kantumruy Pro|sans-serif"],
  ["kapakana", "Kapakana|handwriting"],
  ["karantina", "Karantina|display"],
  ["karla", "Karla|sans-serif"],
  ["karla tamil inclined", "Karla Tamil Inclined|sans-serif"],
  ["karla tamil upright", "Karla Tamil Upright|sans-serif"],
  ["karma", "Karma|serif"],
  ["katibeh", "Katibeh|display"],
  ["kaushan script", "Kaushan Script|handwriting"],
  ["kavivanar", "Kavivanar|handwriting"],
  ["kavoon", "Kavoon|display"],
  ["kay pho du", "Kay Pho Du|serif"],
  ["kdam thmor pro", "Kdam Thmor Pro|sans-serif"],
  ["keania one", "Keania One|display"],
  ["kedebideri", "Kedebideri|sans-serif"],
  ["kelly slab", "Kelly Slab|display"],
  ["kenia", "Kenia|display"],
  ["khand", "Khand|sans-serif"],
  ["khmer", "Khmer|sans-serif"],
  ["khula", "Khula|sans-serif"],
  ["kings", "Kings|handwriting"],
  ["kirang haerang", "Kirang Haerang|display"],
  ["kite one", "Kite One|sans-serif"],
  ["kiwi maru", "Kiwi Maru|serif"],
  ["klee one", "Klee One|handwriting"],
  ["knewave", "Knewave|display"],
  ["kodchasan", "Kodchasan|sans-serif"],
  ["kode mono", "Kode Mono|monospace"],
  ["koh santepheap", "Koh Santepheap|serif"],
  ["koho", "KoHo|sans-serif"],
  ["kolker brush", "Kolker Brush|handwriting"],
  ["konkhmer sleokchher", "Konkhmer Sleokchher|display"],
  ["kosugi", "Kosugi|sans-serif"],
  ["kosugi maru", "Kosugi Maru|sans-serif"],
  ["kotta one", "Kotta One|serif"],
  ["koulen", "Koulen|display"],
  ["kranky", "Kranky|display"],
  ["kreon", "Kreon|serif"],
  ["kristi", "Kristi|handwriting"],
  ["krona one", "Krona One|sans-serif"],
  ["krub", "Krub|sans-serif"],
  ["kufam", "Kufam|sans-serif"],
  ["kulim park", "Kulim Park|sans-serif"],
  ["kumar one", "Kumar One|display"],
  ["kumar one outline", "Kumar One Outline|display"],
  ["kumbh sans", "Kumbh Sans|sans-serif"],
  ["kurale", "Kurale|serif"],
  ["la belle aurore", "La Belle Aurore|handwriting"],
  ["labrada", "Labrada|serif"],
  ["lacquer", "Lacquer|display"],
  ["laila", "Laila|serif"],
  ["lakki reddy", "Lakki Reddy|handwriting"],
  ["lalezar", "Lalezar|sans-serif"],
  ["lancelot", "Lancelot|display"],
  ["langar", "Langar|display"],
  ["lateef", "Lateef|serif"],
  ["lato", "Lato|sans-serif"],
  ["lavishly yours", "Lavishly Yours|handwriting"],
  ["league gothic", "League Gothic|sans-serif"],
  ["league script", "League Script|handwriting"],
  ["league spartan", "League Spartan|sans-serif"],
  ["leckerli one", "Leckerli One|handwriting"],
  ["ledger", "Ledger|serif"],
  ["lekton", "Lekton|monospace"],
  ["lemon", "Lemon|display"],
  ["lemonada", "Lemonada|display"],
  ["lexend", "Lexend|sans-serif"],
  ["lexend deca", "Lexend Deca|sans-serif"],
  ["lexend exa", "Lexend Exa|sans-serif"],
  ["lexend giga", "Lexend Giga|sans-serif"],
  ["lexend mega", "Lexend Mega|sans-serif"],
  ["lexend peta", "Lexend Peta|sans-serif"],
  ["lexend tera", "Lexend Tera|sans-serif"],
  ["lexend zetta", "Lexend Zetta|sans-serif"],
  ["libertinus keyboard", "Libertinus Keyboard|display"],
  ["libertinus math", "Libertinus Math|display"],
  ["libertinus mono", "Libertinus Mono|monospace"],
  ["libertinus sans", "Libertinus Sans|sans-serif"],
  ["libertinus serif", "Libertinus Serif|serif"],
  ["libertinus serif display", "Libertinus Serif Display|display"],
  ["libre barcode 128", "Libre Barcode 128|display"],
  ["libre barcode 128 text", "Libre Barcode 128 Text|display"],
  ["libre barcode 39", "Libre Barcode 39|display"],
  ["libre barcode 39 extended", "Libre Barcode 39 Extended|display"],
  ["libre barcode 39 extended text", "Libre Barcode 39 Extended Text|display"],
  ["libre barcode 39 text", "Libre Barcode 39 Text|display"],
  ["libre barcode ean13 text", "Libre Barcode EAN13 Text|display"],
  ["libre baskerville", "Libre Baskerville|serif"],
  ["libre bodoni", "Libre Bodoni|serif"],
  ["libre caslon display", "Libre Caslon Display|serif"],
  ["libre caslon text", "Libre Caslon Text|serif"],
  ["libre franklin", "Libre Franklin|sans-serif"],
  ["licorice", "Licorice|handwriting"],
  ["life savers", "Life Savers|display"],
  ["lilex", "Lilex|monospace"],
  ["lilita one", "Lilita One|display"],
  ["lily script one", "Lily Script One|display"],
  ["limelight", "Limelight|display"],
  ["linden hill", "Linden Hill|serif"],
  ["line seed jp", "LINE Seed JP|sans-serif"],
  ["linefont", "Linefont|display"],
  ["lisu bosa", "Lisu Bosa|serif"],
  ["liter", "Liter|sans-serif"],
  ["literata", "Literata|serif"],
  ["liu jian mao cao", "Liu Jian Mao Cao|handwriting"],
  ["livvic", "Livvic|sans-serif"],
  ["lobster", "Lobster|display"],
  ["lobster two", "Lobster Two|display"],
  ["londrina outline", "Londrina Outline|display"],
  ["londrina shadow", "Londrina Shadow|display"],
  ["londrina sketch", "Londrina Sketch|display"],
  ["londrina solid", "Londrina Solid|display"],
  ["long cang", "Long Cang|handwriting"],
  ["lora", "Lora|serif"],
  ["love light", "Love Light|handwriting"],
  ["love ya like a sister", "Love Ya Like A Sister|display"],
  ["loved by the king", "Loved by the King|handwriting"],
  ["lovers quarrel", "Lovers Quarrel|handwriting"],
  ["luckiest guy", "Luckiest Guy|display"],
  ["lugrasimo", "Lugrasimo|handwriting"],
  ["lumanosimo", "Lumanosimo|handwriting"],
  ["lunasima", "Lunasima|sans-serif"],
  ["lusitana", "Lusitana|serif"],
  ["lustria", "Lustria|serif"],
  ["luxurious roman", "Luxurious Roman|display"],
  ["luxurious script", "Luxurious Script|handwriting"],
  ["lxgw marker gothic", "LXGW Marker Gothic|sans-serif"],
  ["lxgw wenkai mono tc", "LXGW WenKai Mono TC|monospace"],
  ["lxgw wenkai tc", "LXGW WenKai TC|handwriting"],
  ["m plus 1", "M PLUS 1|sans-serif"],
  ["m plus 1 code", "M PLUS 1 Code|monospace"],
  ["m plus 1p", "M PLUS 1p|sans-serif"],
  ["m plus 2", "M PLUS 2|sans-serif"],
  ["m plus code latin", "M PLUS Code Latin|sans-serif"],
  ["m plus rounded 1c", "M PLUS Rounded 1c|sans-serif"],
  ["ma shan zheng", "Ma Shan Zheng|handwriting"],
  ["macondo", "Macondo|display"],
  ["macondo swash caps", "Macondo Swash Caps|display"],
  ["mada", "Mada|sans-serif"],
  ["madimi one", "Madimi One|sans-serif"],
  ["magra", "Magra|sans-serif"],
  ["maiden orange", "Maiden Orange|serif"],
  ["maitree", "Maitree|serif"],
  ["major mono display", "Major Mono Display|monospace"],
  ["mako", "Mako|sans-serif"],
  ["mali", "Mali|handwriting"],
  ["mallanna", "Mallanna|sans-serif"],
  ["maname", "Maname|serif"],
  ["mandali", "Mandali|sans-serif"],
  ["manjari", "Manjari|sans-serif"],
  ["manrope", "Manrope|sans-serif"],
  ["mansalva", "Mansalva|handwriting"],
  ["manuale", "Manuale|serif"],
  ["manufacturing consent", "Manufacturing Consent|display"],
  ["marcellus", "Marcellus|serif"],
  ["marcellus sc", "Marcellus SC|serif"],
  ["marck script", "Marck Script|handwriting"],
  ["margarine", "Margarine|display"],
  ["marhey", "Marhey|display"],
  ["markazi text", "Markazi Text|serif"],
  ["marko one", "Marko One|serif"],
  ["marmelad", "Marmelad|sans-serif"],
  ["martel", "Martel|serif"],
  ["martel sans", "Martel Sans|sans-serif"],
  ["martian mono", "Martian Mono|monospace"],
  ["marvel", "Marvel|sans-serif"],
  ["matangi", "Matangi|sans-serif"],
  ["mate", "Mate|serif"],
  ["mate sc", "Mate SC|serif"],
  ["matemasie", "Matemasie|sans-serif"],
  ["maven pro", "Maven Pro|sans-serif"],
  ["mclaren", "McLaren|display"],
  ["mea culpa", "Mea Culpa|handwriting"],
  ["meddon", "Meddon|handwriting"],
  ["medievalsharp", "MedievalSharp|display"],
  ["medula one", "Medula One|display"],
  ["meera inimai", "Meera Inimai|sans-serif"],
  ["megrim", "Megrim|display"],
  ["meie script", "Meie Script|handwriting"],
  ["menbere", "Menbere|sans-serif"],
  ["meow script", "Meow Script|handwriting"],
  ["merienda", "Merienda|handwriting"],
  ["merriweather", "Merriweather|serif"],
  ["merriweather sans", "Merriweather Sans|sans-serif"],
  ["metal", "Metal|display"],
  ["metal mania", "Metal Mania|display"],
  ["metamorphous", "Metamorphous|display"],
  ["metrophobic", "Metrophobic|sans-serif"],
  ["michroma", "Michroma|sans-serif"],
  ["micro 5", "Micro 5|display"],
  ["micro 5 charted", "Micro 5 Charted|display"],
  ["milonga", "Milonga|display"],
  ["miltonian", "Miltonian|display"],
  ["miltonian tattoo", "Miltonian Tattoo|display"],
  ["mina", "Mina|sans-serif"],
  ["mingzat", "Mingzat|sans-serif"],
  ["miniver", "Miniver|display"],
  ["miranda sans", "Miranda Sans|sans-serif"],
  ["miriam libre", "Miriam Libre|sans-serif"],
  ["mirza", "Mirza|serif"],
  ["miss fajardose", "Miss Fajardose|handwriting"],
  ["mitr", "Mitr|sans-serif"],
  ["mochiy pop one", "Mochiy Pop One|sans-serif"],
  ["mochiy pop p one", "Mochiy Pop P One|sans-serif"],
  ["modak", "Modak|display"],
  ["modern antiqua", "Modern Antiqua|display"],
  ["moderustic", "Moderustic|sans-serif"],
  ["mogra", "Mogra|display"],
  ["mohave", "Mohave|sans-serif"],
  ["moirai one", "Moirai One|display"],
  ["molengo", "Molengo|sans-serif"],
  ["molle", "Molle|handwriting"],
  ["momo signature", "Momo Signature|sans-serif"],
  ["momo trust display", "Momo Trust Display|sans-serif"],
  ["momo trust sans", "Momo Trust Sans|sans-serif"],
  ["mona sans", "Mona Sans|sans-serif"],
  ["monda", "Monda|sans-serif"],
  ["monofett", "Monofett|monospace"],
  ["monomakh", "Monomakh|display"],
  ["monomaniac one", "Monomaniac One|sans-serif"],
  ["monoton", "Monoton|display"],
  ["monsieur la doulaise", "Monsieur La Doulaise|handwriting"],
  ["montaga", "Montaga|serif"],
  ["montagu slab", "Montagu Slab|serif"],
  ["montecarlo", "MonteCarlo|handwriting"],
  ["montez", "Montez|handwriting"],
  ["montserrat", "Montserrat|sans-serif"],
  ["montserrat alternates", "Montserrat Alternates|sans-serif"],
  ["montserrat underline", "Montserrat Underline|sans-serif"],
  ["moo lah lah", "Moo Lah Lah|display"],
  ["mooli", "Mooli|sans-serif"],
  ["moon dance", "Moon Dance|handwriting"],
  ["moul", "Moul|display"],
  ["moulpali", "Moulpali|sans-serif"],
  ["mountains of christmas", "Mountains of Christmas|display"],
  ["mouse memoirs", "Mouse Memoirs|sans-serif"],
  ["mozilla headline", "Mozilla Headline|sans-serif"],
  ["mozilla text", "Mozilla Text|sans-serif"],
  ["mr bedfort", "Mr Bedfort|handwriting"],
  ["mr dafoe", "Mr Dafoe|handwriting"],
  ["mr de haviland", "Mr De Haviland|handwriting"],
  ["mrs saint delafield", "Mrs Saint Delafield|handwriting"],
  ["mrs sheppards", "Mrs Sheppards|handwriting"],
  ["ms madi", "Ms Madi|handwriting"],
  ["mukta", "Mukta|sans-serif"],
  ["mukta mahee", "Mukta Mahee|sans-serif"],
  ["mukta malar", "Mukta Malar|sans-serif"],
  ["mukta vaani", "Mukta Vaani|sans-serif"],
  ["mulish", "Mulish|sans-serif"],
  ["murecho", "Murecho|sans-serif"],
  ["museomoderno", "MuseoModerno|display"],
  ["my soul", "My Soul|handwriting"],
  ["mynerve", "Mynerve|handwriting"],
  ["mystery quest", "Mystery Quest|display"],
  ["nabla", "Nabla|display"],
  ["namdhinggo", "Namdhinggo|serif"],
  ["nanum brush script", "Nanum Brush Script|handwriting"],
  ["nanum gothic", "Nanum Gothic|sans-serif"],
  ["nanum gothic coding", "Nanum Gothic Coding|handwriting"],
  ["nanum myeongjo", "Nanum Myeongjo|serif"],
  ["nanum pen script", "Nanum Pen Script|handwriting"],
  ["narnoor", "Narnoor|sans-serif"],
  ["nata sans", "Nata Sans|sans-serif"],
  ["national park", "National Park|sans-serif"],
  ["neonderthaw", "Neonderthaw|handwriting"],
  ["nerko one", "Nerko One|handwriting"],
  ["neucha", "Neucha|handwriting"],
  ["neuton", "Neuton|serif"],
  ["new amsterdam", "New Amsterdam|sans-serif"],
  ["new rocker", "New Rocker|display"],
  ["new tegomin", "New Tegomin|serif"],
  ["news cycle", "News Cycle|sans-serif"],
  ["newsreader", "Newsreader|serif"],
  ["niconne", "Niconne|handwriting"],
  ["niramit", "Niramit|sans-serif"],
  ["nixie one", "Nixie One|display"],
  ["nobile", "Nobile|sans-serif"],
  ["nokora", "Nokora|sans-serif"],
  ["norican", "Norican|handwriting"],
  ["nosifer", "Nosifer|display"],
  ["notable", "Notable|sans-serif"],
  ["nothing you could do", "Nothing You Could Do|handwriting"],
  ["noticia text", "Noticia Text|serif"],
  ["noto color emoji", "Noto Color Emoji|sans-serif"],
  ["noto emoji", "Noto Emoji|sans-serif"],
  ["noto kufi arabic", "Noto Kufi Arabic|sans-serif"],
  ["noto music", "Noto Music|sans-serif"],
  ["noto naskh arabic", "Noto Naskh Arabic|serif"],
  ["noto nastaliq urdu", "Noto Nastaliq Urdu|serif"],
  ["noto rashi hebrew", "Noto Rashi Hebrew|serif"],
  ["noto sans", "Noto Sans|sans-serif"],
  ["noto sans adlam", "Noto Sans Adlam|sans-serif"],
  ["noto sans adlam unjoined", "Noto Sans Adlam Unjoined|sans-serif"],
  ["noto sans anatolian hieroglyphs", "Noto Sans Anatolian Hieroglyphs|sans-serif"],
  ["noto sans arabic", "Noto Sans Arabic|sans-serif"],
  ["noto sans armenian", "Noto Sans Armenian|sans-serif"],
  ["noto sans avestan", "Noto Sans Avestan|sans-serif"],
  ["noto sans balinese", "Noto Sans Balinese|sans-serif"],
  ["noto sans bamum", "Noto Sans Bamum|sans-serif"],
  ["noto sans bassa vah", "Noto Sans Bassa Vah|sans-serif"],
  ["noto sans batak", "Noto Sans Batak|sans-serif"],
  ["noto sans bengali", "Noto Sans Bengali|sans-serif"],
  ["noto sans bhaiksuki", "Noto Sans Bhaiksuki|sans-serif"],
  ["noto sans brahmi", "Noto Sans Brahmi|sans-serif"],
  ["noto sans buginese", "Noto Sans Buginese|sans-serif"],
  ["noto sans buhid", "Noto Sans Buhid|sans-serif"],
  ["noto sans canadian aboriginal", "Noto Sans Canadian Aboriginal|sans-serif"],
  ["noto sans carian", "Noto Sans Carian|sans-serif"],
  ["noto sans caucasian albanian", "Noto Sans Caucasian Albanian|sans-serif"],
  ["noto sans chakma", "Noto Sans Chakma|sans-serif"],
  ["noto sans cham", "Noto Sans Cham|sans-serif"],
  ["noto sans cherokee", "Noto Sans Cherokee|sans-serif"],
  ["noto sans chorasmian", "Noto Sans Chorasmian|sans-serif"],
  ["noto sans coptic", "Noto Sans Coptic|sans-serif"],
  ["noto sans cuneiform", "Noto Sans Cuneiform|sans-serif"],
  ["noto sans cypriot", "Noto Sans Cypriot|sans-serif"],
  ["noto sans cypro minoan", "Noto Sans Cypro Minoan|sans-serif"],
  ["noto sans deseret", "Noto Sans Deseret|sans-serif"],
  ["noto sans devanagari", "Noto Sans Devanagari|sans-serif"],
  ["noto sans display", "Noto Sans Display|sans-serif"],
  ["noto sans duployan", "Noto Sans Duployan|sans-serif"],
  ["noto sans egyptian hieroglyphs", "Noto Sans Egyptian Hieroglyphs|sans-serif"],
  ["noto sans elbasan", "Noto Sans Elbasan|sans-serif"],
  ["noto sans elymaic", "Noto Sans Elymaic|sans-serif"],
  ["noto sans ethiopic", "Noto Sans Ethiopic|sans-serif"],
  ["noto sans georgian", "Noto Sans Georgian|sans-serif"],
  ["noto sans glagolitic", "Noto Sans Glagolitic|sans-serif"],
  ["noto sans gothic", "Noto Sans Gothic|sans-serif"],
  ["noto sans grantha", "Noto Sans Grantha|sans-serif"],
  ["noto sans gujarati", "Noto Sans Gujarati|sans-serif"],
  ["noto sans gunjala gondi", "Noto Sans Gunjala Gondi|sans-serif"],
  ["noto sans gurmukhi", "Noto Sans Gurmukhi|sans-serif"],
  ["noto sans hanifi rohingya", "Noto Sans Hanifi Rohingya|sans-serif"],
  ["noto sans hanunoo", "Noto Sans Hanunoo|sans-serif"],
  ["noto sans hatran", "Noto Sans Hatran|sans-serif"],
  ["noto sans hebrew", "Noto Sans Hebrew|sans-serif"],
  ["noto sans hk", "Noto Sans HK|sans-serif"],
  ["noto sans imperial aramaic", "Noto Sans Imperial Aramaic|sans-serif"],
  ["noto sans indic siyaq numbers", "Noto Sans Indic Siyaq Numbers|sans-serif"],
  ["noto sans inscriptional pahlavi", "Noto Sans Inscriptional Pahlavi|sans-serif"],
  ["noto sans inscriptional parthian", "Noto Sans Inscriptional Parthian|sans-serif"],
  ["noto sans javanese", "Noto Sans Javanese|sans-serif"],
  ["noto sans jp", "Noto Sans JP|sans-serif"],
  ["noto sans kaithi", "Noto Sans Kaithi|sans-serif"],
  ["noto sans kannada", "Noto Sans Kannada|sans-serif"],
  ["noto sans kawi", "Noto Sans Kawi|sans-serif"],
  ["noto sans kayah li", "Noto Sans Kayah Li|sans-serif"],
  ["noto sans kharoshthi", "Noto Sans Kharoshthi|sans-serif"],
  ["noto sans khmer", "Noto Sans Khmer|sans-serif"],
  ["noto sans khojki", "Noto Sans Khojki|sans-serif"],
  ["noto sans khudawadi", "Noto Sans Khudawadi|sans-serif"],
  ["noto sans kr", "Noto Sans KR|sans-serif"],
  ["noto sans lao", "Noto Sans Lao|sans-serif"],
  ["noto sans lao looped", "Noto Sans Lao Looped|sans-serif"],
  ["noto sans lepcha", "Noto Sans Lepcha|sans-serif"],
  ["noto sans limbu", "Noto Sans Limbu|sans-serif"],
  ["noto sans linear a", "Noto Sans Linear A|sans-serif"],
  ["noto sans linear b", "Noto Sans Linear B|sans-serif"],
  ["noto sans lisu", "Noto Sans Lisu|sans-serif"],
  ["noto sans lycian", "Noto Sans Lycian|sans-serif"],
  ["noto sans lydian", "Noto Sans Lydian|sans-serif"],
  ["noto sans mahajani", "Noto Sans Mahajani|sans-serif"],
  ["noto sans malayalam", "Noto Sans Malayalam|sans-serif"],
  ["noto sans mandaic", "Noto Sans Mandaic|sans-serif"],
  ["noto sans manichaean", "Noto Sans Manichaean|sans-serif"],
  ["noto sans marchen", "Noto Sans Marchen|sans-serif"],
  ["noto sans masaram gondi", "Noto Sans Masaram Gondi|sans-serif"],
  ["noto sans math", "Noto Sans Math|sans-serif"],
  ["noto sans mayan numerals", "Noto Sans Mayan Numerals|sans-serif"],
  ["noto sans medefaidrin", "Noto Sans Medefaidrin|sans-serif"],
  ["noto sans meetei mayek", "Noto Sans Meetei Mayek|sans-serif"],
  ["noto sans mende kikakui", "Noto Sans Mende Kikakui|sans-serif"],
  ["noto sans meroitic", "Noto Sans Meroitic|sans-serif"],
  ["noto sans miao", "Noto Sans Miao|sans-serif"],
  ["noto sans modi", "Noto Sans Modi|sans-serif"],
  ["noto sans mongolian", "Noto Sans Mongolian|sans-serif"],
  ["noto sans mono", "Noto Sans Mono|sans-serif"],
  ["noto sans mro", "Noto Sans Mro|sans-serif"],
  ["noto sans multani", "Noto Sans Multani|sans-serif"],
  ["noto sans myanmar", "Noto Sans Myanmar|sans-serif"],
  ["noto sans nabataean", "Noto Sans Nabataean|sans-serif"],
  ["noto sans nag mundari", "Noto Sans Nag Mundari|sans-serif"],
  ["noto sans nandinagari", "Noto Sans Nandinagari|sans-serif"],
  ["noto sans new tai lue", "Noto Sans New Tai Lue|sans-serif"],
  ["noto sans newa", "Noto Sans Newa|sans-serif"],
  ["noto sans nko", "Noto Sans NKo|sans-serif"],
  ["noto sans nko unjoined", "Noto Sans NKo Unjoined|sans-serif"],
  ["noto sans nushu", "Noto Sans Nushu|sans-serif"],
  ["noto sans ogham", "Noto Sans Ogham|sans-serif"],
  ["noto sans ol chiki", "Noto Sans Ol Chiki|sans-serif"],
  ["noto sans old hungarian", "Noto Sans Old Hungarian|sans-serif"],
  ["noto sans old italic", "Noto Sans Old Italic|sans-serif"],
  ["noto sans old north arabian", "Noto Sans Old North Arabian|sans-serif"],
  ["noto sans old permic", "Noto Sans Old Permic|sans-serif"],
  ["noto sans old persian", "Noto Sans Old Persian|sans-serif"],
  ["noto sans old sogdian", "Noto Sans Old Sogdian|sans-serif"],
  ["noto sans old south arabian", "Noto Sans Old South Arabian|sans-serif"],
  ["noto sans old turkic", "Noto Sans Old Turkic|sans-serif"],
  ["noto sans oriya", "Noto Sans Oriya|sans-serif"],
  ["noto sans osage", "Noto Sans Osage|sans-serif"],
  ["noto sans osmanya", "Noto Sans Osmanya|sans-serif"],
  ["noto sans pahawh hmong", "Noto Sans Pahawh Hmong|sans-serif"],
  ["noto sans palmyrene", "Noto Sans Palmyrene|sans-serif"],
  ["noto sans pau cin hau", "Noto Sans Pau Cin Hau|sans-serif"],
  ["noto sans phagspa", "Noto Sans PhagsPa|sans-serif"],
  ["noto sans phoenician", "Noto Sans Phoenician|sans-serif"],
  ["noto sans psalter pahlavi", "Noto Sans Psalter Pahlavi|sans-serif"],
  ["noto sans rejang", "Noto Sans Rejang|sans-serif"],
  ["noto sans runic", "Noto Sans Runic|sans-serif"],
  ["noto sans samaritan", "Noto Sans Samaritan|sans-serif"],
  ["noto sans saurashtra", "Noto Sans Saurashtra|sans-serif"],
  ["noto sans sc", "Noto Sans SC|sans-serif"],
  ["noto sans sharada", "Noto Sans Sharada|sans-serif"],
  ["noto sans shavian", "Noto Sans Shavian|sans-serif"],
  ["noto sans siddham", "Noto Sans Siddham|sans-serif"],
  ["noto sans signwriting", "Noto Sans SignWriting|sans-serif"],
  ["noto sans sinhala", "Noto Sans Sinhala|sans-serif"],
  ["noto sans sogdian", "Noto Sans Sogdian|sans-serif"],
  ["noto sans sora sompeng", "Noto Sans Sora Sompeng|sans-serif"],
  ["noto sans soyombo", "Noto Sans Soyombo|sans-serif"],
  ["noto sans sundanese", "Noto Sans Sundanese|sans-serif"],
  ["noto sans sunuwar", "Noto Sans Sunuwar|sans-serif"],
  ["noto sans syloti nagri", "Noto Sans Syloti Nagri|sans-serif"],
  ["noto sans symbols", "Noto Sans Symbols|sans-serif"],
  ["noto sans symbols 2", "Noto Sans Symbols 2|sans-serif"],
  ["noto sans syriac", "Noto Sans Syriac|sans-serif"],
  ["noto sans syriac eastern", "Noto Sans Syriac Eastern|sans-serif"],
  ["noto sans syriac western", "Noto Sans Syriac Western|sans-serif"],
  ["noto sans tagalog", "Noto Sans Tagalog|sans-serif"],
  ["noto sans tagbanwa", "Noto Sans Tagbanwa|sans-serif"],
  ["noto sans tai le", "Noto Sans Tai Le|sans-serif"],
  ["noto sans tai tham", "Noto Sans Tai Tham|sans-serif"],
  ["noto sans tai viet", "Noto Sans Tai Viet|sans-serif"],
  ["noto sans takri", "Noto Sans Takri|sans-serif"],
  ["noto sans tamil", "Noto Sans Tamil|sans-serif"],
  ["noto sans tamil supplement", "Noto Sans Tamil Supplement|sans-serif"],
  ["noto sans tangsa", "Noto Sans Tangsa|sans-serif"],
  ["noto sans tc", "Noto Sans TC|sans-serif"],
  ["noto sans telugu", "Noto Sans Telugu|sans-serif"],
  ["noto sans thaana", "Noto Sans Thaana|sans-serif"],
  ["noto sans thai", "Noto Sans Thai|sans-serif"],
  ["noto sans thai looped", "Noto Sans Thai Looped|sans-serif"],
  ["noto sans tifinagh", "Noto Sans Tifinagh|sans-serif"],
  ["noto sans tirhuta", "Noto Sans Tirhuta|sans-serif"],
  ["noto sans ugaritic", "Noto Sans Ugaritic|sans-serif"],
  ["noto sans vai", "Noto Sans Vai|sans-serif"],
  ["noto sans vithkuqi", "Noto Sans Vithkuqi|sans-serif"],
  ["noto sans wancho", "Noto Sans Wancho|sans-serif"],
  ["noto sans warang citi", "Noto Sans Warang Citi|sans-serif"],
  ["noto sans yi", "Noto Sans Yi|sans-serif"],
  ["noto sans zanabazar square", "Noto Sans Zanabazar Square|sans-serif"],
  ["noto serif", "Noto Serif|serif"],
  ["noto serif ahom", "Noto Serif Ahom|serif"],
  ["noto serif armenian", "Noto Serif Armenian|serif"],
  ["noto serif balinese", "Noto Serif Balinese|serif"],
  ["noto serif bengali", "Noto Serif Bengali|serif"],
  ["noto serif devanagari", "Noto Serif Devanagari|serif"],
  ["noto serif display", "Noto Serif Display|serif"],
  ["noto serif dives akuru", "Noto Serif Dives Akuru|serif"],
  ["noto serif dogra", "Noto Serif Dogra|serif"],
  ["noto serif ethiopic", "Noto Serif Ethiopic|serif"],
  ["noto serif georgian", "Noto Serif Georgian|serif"],
  ["noto serif grantha", "Noto Serif Grantha|serif"],
  ["noto serif gujarati", "Noto Serif Gujarati|serif"],
  ["noto serif gurmukhi", "Noto Serif Gurmukhi|serif"],
  ["noto serif hebrew", "Noto Serif Hebrew|serif"],
  ["noto serif hentaigana", "Noto Serif Hentaigana|serif"],
  ["noto serif hk", "Noto Serif HK|serif"],
  ["noto serif jp", "Noto Serif JP|serif"],
  ["noto serif kannada", "Noto Serif Kannada|serif"],
  ["noto serif khitan small script", "Noto Serif Khitan Small Script|serif"],
  ["noto serif khmer", "Noto Serif Khmer|serif"],
  ["noto serif khojki", "Noto Serif Khojki|serif"],
  ["noto serif kr", "Noto Serif KR|serif"],
  ["noto serif lao", "Noto Serif Lao|serif"],
  ["noto serif makasar", "Noto Serif Makasar|serif"],
  ["noto serif malayalam", "Noto Serif Malayalam|serif"],
  ["noto serif myanmar", "Noto Serif Myanmar|serif"],
  ["noto serif np hmong", "Noto Serif NP Hmong|serif"],
  ["noto serif old uyghur", "Noto Serif Old Uyghur|serif"],
  ["noto serif oriya", "Noto Serif Oriya|serif"],
  ["noto serif ottoman siyaq", "Noto Serif Ottoman Siyaq|serif"],
  ["noto serif sc", "Noto Serif SC|serif"],
  ["noto serif sinhala", "Noto Serif Sinhala|serif"],
  ["noto serif tamil", "Noto Serif Tamil|serif"],
  ["noto serif tangut", "Noto Serif Tangut|serif"],
  ["noto serif tc", "Noto Serif TC|serif"],
  ["noto serif telugu", "Noto Serif Telugu|serif"],
  ["noto serif thai", "Noto Serif Thai|serif"],
  ["noto serif tibetan", "Noto Serif Tibetan|serif"],
  ["noto serif todhri", "Noto Serif Todhri|serif"],
  ["noto serif toto", "Noto Serif Toto|serif"],
  ["noto serif vithkuqi", "Noto Serif Vithkuqi|serif"],
  ["noto serif yezidi", "Noto Serif Yezidi|serif"],
  ["noto traditional nushu", "Noto Traditional Nushu|sans-serif"],
  ["noto znamenny musical notation", "Noto Znamenny Musical Notation|sans-serif"],
  ["nova cut", "Nova Cut|display"],
  ["nova flat", "Nova Flat|display"],
  ["nova mono", "Nova Mono|monospace"],
  ["nova oval", "Nova Oval|display"],
  ["nova round", "Nova Round|display"],
  ["nova script", "Nova Script|display"],
  ["nova slim", "Nova Slim|display"],
  ["nova square", "Nova Square|display"],
  ["ntr", "NTR|sans-serif"],
  ["numans", "Numans|sans-serif"],
  ["nunito", "Nunito|sans-serif"],
  ["nunito sans", "Nunito Sans|sans-serif"],
  ["nuosu sil", "Nuosu SIL|sans-serif"],
  ["odibee sans", "Odibee Sans|display"],
  ["odor mean chey", "Odor Mean Chey|serif"],
  ["offside", "Offside|display"],
  ["oi", "Oi|display"],
  ["ojuju", "Ojuju|sans-serif"],
  ["old standard tt", "Old Standard TT|serif"],
  ["oldenburg", "Oldenburg|display"],
  ["ole", "Ole|handwriting"],
  ["oleo script", "Oleo Script|display"],
  ["oleo script swash caps", "Oleo Script Swash Caps|display"],
  ["onest", "Onest|sans-serif"],
  ["oooh baby", "Oooh Baby|handwriting"],
  ["open sans", "Open Sans|sans-serif"],
  ["oranienbaum", "Oranienbaum|serif"],
  ["orbit", "Orbit|sans-serif"],
  ["orbitron", "Orbitron|sans-serif"],
  ["oregano", "Oregano|display"],
  ["orelega one", "Orelega One|display"],
  ["orienta", "Orienta|sans-serif"],
  ["original surfer", "Original Surfer|display"],
  ["oswald", "Oswald|sans-serif"],
  ["outfit", "Outfit|sans-serif"],
  ["over the rainbow", "Over the Rainbow|handwriting"],
  ["overlock", "Overlock|display"],
  ["overlock sc", "Overlock SC|display"],
  ["overpass", "Overpass|sans-serif"],
  ["overpass mono", "Overpass Mono|monospace"],
  ["ovo", "Ovo|serif"],
  ["oxanium", "Oxanium|display"],
  ["oxygen", "Oxygen|sans-serif"],
  ["oxygen mono", "Oxygen Mono|monospace"],
  ["pacifico", "Pacifico|handwriting"],
  ["padauk", "Padauk|sans-serif"],
  ["padyakke expanded one", "Padyakke Expanded One|serif"],
  ["palanquin", "Palanquin|sans-serif"],
  ["palanquin dark", "Palanquin Dark|sans-serif"],
  ["palette mosaic", "Palette Mosaic|display"],
  ["pangolin", "Pangolin|handwriting"],
  ["paprika", "Paprika|display"],
  ["parastoo", "Parastoo|serif"],
  ["parisienne", "Parisienne|handwriting"],
  ["parkinsans", "Parkinsans|sans-serif"],
  ["passero one", "Passero One|display"],
  ["passion one", "Passion One|display"],
  ["passions conflict", "Passions Conflict|handwriting"],
  ["pathway extreme", "Pathway Extreme|sans-serif"],
  ["pathway gothic one", "Pathway Gothic One|sans-serif"],
  ["patrick hand", "Patrick Hand|handwriting"],
  ["patrick hand sc", "Patrick Hand SC|handwriting"],
  ["pattaya", "Pattaya|sans-serif"],
  ["patua one", "Patua One|display"],
  ["pavanam", "Pavanam|sans-serif"],
  ["paytone one", "Paytone One|sans-serif"],
  ["peddana", "Peddana|serif"],
  ["peralta", "Peralta|serif"],
  ["permanent marker", "Permanent Marker|handwriting"],
  ["petemoss", "Petemoss|handwriting"],
  ["petit formal script", "Petit Formal Script|handwriting"],
  ["petrona", "Petrona|serif"],
  ["phetsarath", "Phetsarath|sans-serif"],
  ["philosopher", "Philosopher|sans-serif"],
  ["phudu", "Phudu|display"],
  ["piazzolla", "Piazzolla|serif"],
  ["piedra", "Piedra|display"],
  ["pinyon script", "Pinyon Script|handwriting"],
  ["pirata one", "Pirata One|display"],
  ["pixelify sans", "Pixelify Sans|display"],
  ["plaster", "Plaster|display"],
  ["platypi", "Platypi|serif"],
  ["play", "Play|sans-serif"],
  ["playball", "Playball|display"],
  ["playfair", "Playfair|serif"],
  ["playfair display", "Playfair Display|serif"],
  ["playfair display sc", "Playfair Display SC|serif"],
  ["playpen sans", "Playpen Sans|handwriting"],
  ["playpen sans arabic", "Playpen Sans Arabic|handwriting"],
  ["playpen sans deva", "Playpen Sans Deva|handwriting"],
  ["playpen sans hebrew", "Playpen Sans Hebrew|handwriting"],
  ["playpen sans thai", "Playpen Sans Thai|handwriting"],
  ["playwrite ar", "Playwrite AR|handwriting"],
  ["playwrite ar guides", "Playwrite AR Guides|handwriting"],
  ["playwrite at", "Playwrite AT|handwriting"],
  ["playwrite at guides", "Playwrite AT Guides|handwriting"],
  ["playwrite au nsw", "Playwrite AU NSW|handwriting"],
  ["playwrite au nsw guides", "Playwrite AU NSW Guides|handwriting"],
  ["playwrite au qld", "Playwrite AU QLD|handwriting"],
  ["playwrite au qld guides", "Playwrite AU QLD Guides|handwriting"],
  ["playwrite au sa", "Playwrite AU SA|handwriting"],
  ["playwrite au sa guides", "Playwrite AU SA Guides|handwriting"],
  ["playwrite au tas", "Playwrite AU TAS|handwriting"],
  ["playwrite au tas guides", "Playwrite AU TAS Guides|handwriting"],
  ["playwrite au vic", "Playwrite AU VIC|handwriting"],
  ["playwrite au vic guides", "Playwrite AU VIC Guides|handwriting"],
  ["playwrite be vlg", "Playwrite BE VLG|handwriting"],
  ["playwrite be vlg guides", "Playwrite BE VLG Guides|handwriting"],
  ["playwrite be wal", "Playwrite BE WAL|handwriting"],
  ["playwrite be wal guides", "Playwrite BE WAL Guides|handwriting"],
  ["playwrite br", "Playwrite BR|handwriting"],
  ["playwrite br guides", "Playwrite BR Guides|handwriting"],
  ["playwrite ca", "Playwrite CA|handwriting"],
  ["playwrite ca guides", "Playwrite CA Guides|handwriting"],
  ["playwrite cl", "Playwrite CL|handwriting"],
  ["playwrite cl guides", "Playwrite CL Guides|handwriting"],
  ["playwrite co", "Playwrite CO|handwriting"],
  ["playwrite co guides", "Playwrite CO Guides|handwriting"],
  ["playwrite cu", "Playwrite CU|handwriting"],
  ["playwrite cu guides", "Playwrite CU Guides|handwriting"],
  ["playwrite cz", "Playwrite CZ|handwriting"],
  ["playwrite cz guides", "Playwrite CZ Guides|handwriting"],
  ["playwrite de grund", "Playwrite DE Grund|handwriting"],
  ["playwrite de grund guides", "Playwrite DE Grund Guides|handwriting"],
  ["playwrite de la", "Playwrite DE LA|handwriting"],
  ["playwrite de la guides", "Playwrite DE LA Guides|handwriting"],
  ["playwrite de sas", "Playwrite DE SAS|handwriting"],
  ["playwrite de sas guides", "Playwrite DE SAS Guides|handwriting"],
  ["playwrite de va", "Playwrite DE VA|handwriting"],
  ["playwrite de va guides", "Playwrite DE VA Guides|handwriting"],
  ["playwrite dk loopet", "Playwrite DK Loopet|handwriting"],
  ["playwrite dk loopet guides", "Playwrite DK Loopet Guides|handwriting"],
  ["playwrite dk uloopet", "Playwrite DK Uloopet|handwriting"],
  ["playwrite dk uloopet guides", "Playwrite DK Uloopet Guides|handwriting"],
  ["playwrite es", "Playwrite ES|handwriting"],
  ["playwrite es deco", "Playwrite ES Deco|handwriting"],
  ["playwrite es deco guides", "Playwrite ES Deco Guides|handwriting"],
  ["playwrite es guides", "Playwrite ES Guides|handwriting"],
  ["playwrite fr moderne", "Playwrite FR Moderne|handwriting"],
  ["playwrite fr moderne guides", "Playwrite FR Moderne Guides|handwriting"],
  ["playwrite fr trad", "Playwrite FR Trad|handwriting"],
  ["playwrite fr trad guides", "Playwrite FR Trad Guides|handwriting"],
  ["playwrite gb j", "Playwrite GB J|handwriting"],
  ["playwrite gb j guides", "Playwrite GB J Guides|handwriting"],
  ["playwrite gb s", "Playwrite GB S|handwriting"],
  ["playwrite gb s guides", "Playwrite GB S Guides|handwriting"],
  ["playwrite hr", "Playwrite HR|handwriting"],
  ["playwrite hr guides", "Playwrite HR Guides|handwriting"],
  ["playwrite hr lijeva", "Playwrite HR Lijeva|handwriting"],
  ["playwrite hr lijeva guides", "Playwrite HR Lijeva Guides|handwriting"],
  ["playwrite hu", "Playwrite HU|handwriting"],
  ["playwrite hu guides", "Playwrite HU Guides|handwriting"],
  ["playwrite id", "Playwrite ID|handwriting"],
  ["playwrite id guides", "Playwrite ID Guides|handwriting"],
  ["playwrite ie", "Playwrite IE|handwriting"],
  ["playwrite ie guides", "Playwrite IE Guides|handwriting"],
  ["playwrite in", "Playwrite IN|handwriting"],
  ["playwrite in guides", "Playwrite IN Guides|handwriting"],
  ["playwrite is", "Playwrite IS|handwriting"],
  ["playwrite is guides", "Playwrite IS Guides|handwriting"],
  ["playwrite it moderna", "Playwrite IT Moderna|handwriting"],
  ["playwrite it moderna guides", "Playwrite IT Moderna Guides|handwriting"],
  ["playwrite it trad", "Playwrite IT Trad|handwriting"],
  ["playwrite it trad guides", "Playwrite IT Trad Guides|handwriting"],
  ["playwrite mx", "Playwrite MX|handwriting"],
  ["playwrite mx guides", "Playwrite MX Guides|handwriting"],
  ["playwrite ng modern", "Playwrite NG Modern|handwriting"],
  ["playwrite ng modern guides", "Playwrite NG Modern Guides|handwriting"],
  ["playwrite nl", "Playwrite NL|handwriting"],
  ["playwrite nl guides", "Playwrite NL Guides|handwriting"],
  ["playwrite no", "Playwrite NO|handwriting"],
  ["playwrite no guides", "Playwrite NO Guides|handwriting"],
  ["playwrite nz", "Playwrite NZ|handwriting"],
  ["playwrite nz basic", "Playwrite NZ Basic|handwriting"],
  ["playwrite nz basic guides", "Playwrite NZ Basic Guides|handwriting"],
  ["playwrite nz guides", "Playwrite NZ Guides|handwriting"],
  ["playwrite pe", "Playwrite PE|handwriting"],
  ["playwrite pe guides", "Playwrite PE Guides|handwriting"],
  ["playwrite pl", "Playwrite PL|handwriting"],
  ["playwrite pl guides", "Playwrite PL Guides|handwriting"],
  ["playwrite pt", "Playwrite PT|handwriting"],
  ["playwrite pt guides", "Playwrite PT Guides|handwriting"],
  ["playwrite ro", "Playwrite RO|handwriting"],
  ["playwrite ro guides", "Playwrite RO Guides|handwriting"],
  ["playwrite sk", "Playwrite SK|handwriting"],
  ["playwrite sk guides", "Playwrite SK Guides|handwriting"],
  ["playwrite tz", "Playwrite TZ|handwriting"],
  ["playwrite tz guides", "Playwrite TZ Guides|handwriting"],
  ["playwrite us modern", "Playwrite US Modern|handwriting"],
  ["playwrite us modern guides", "Playwrite US Modern Guides|handwriting"],
  ["playwrite us trad", "Playwrite US Trad|handwriting"],
  ["playwrite us trad guides", "Playwrite US Trad Guides|handwriting"],
  ["playwrite vn", "Playwrite VN|handwriting"],
  ["playwrite vn guides", "Playwrite VN Guides|handwriting"],
  ["playwrite za", "Playwrite ZA|handwriting"],
  ["playwrite za guides", "Playwrite ZA Guides|handwriting"],
  ["plus jakarta sans", "Plus Jakarta Sans|sans-serif"],
  ["pochaevsk", "Pochaevsk|display"],
  ["podkova", "Podkova|serif"],
  ["poetsen one", "Poetsen One|display"],
  ["poiret one", "Poiret One|display"],
  ["poller one", "Poller One|display"],
  ["poltawski nowy", "Poltawski Nowy|serif"],
  ["poly", "Poly|serif"],
  ["pompiere", "Pompiere|display"],
  ["ponnala", "Ponnala|display"],
  ["ponomar", "Ponomar|display"],
  ["pontano sans", "Pontano Sans|sans-serif"],
  ["poor story", "Poor Story|display"],
  ["poppins", "Poppins|sans-serif"],
  ["port lligat sans", "Port Lligat Sans|sans-serif"],
  ["port lligat slab", "Port Lligat Slab|serif"],
  ["potta one", "Potta One|display"],
  ["pragati narrow", "Pragati Narrow|sans-serif"],
  ["praise", "Praise|handwriting"],
  ["prata", "Prata|serif"],
  ["preahvihear", "Preahvihear|sans-serif"],
  ["press start 2p", "Press Start 2P|display"],
  ["pridi", "Pridi|serif"],
  ["princess sofia", "Princess Sofia|handwriting"],
  ["prociono", "Prociono|serif"],
  ["prompt", "Prompt|sans-serif"],
  ["prosto one", "Prosto One|display"],
  ["protest guerrilla", "Protest Guerrilla|display"],
  ["protest revolution", "Protest Revolution|display"],
  ["protest riot", "Protest Riot|display"],
  ["protest strike", "Protest Strike|display"],
  ["proza libre", "Proza Libre|sans-serif"],
  ["pt mono", "PT Mono|monospace"],
  ["pt sans", "PT Sans|sans-serif"],
  ["pt sans caption", "PT Sans Caption|sans-serif"],
  ["pt sans narrow", "PT Sans Narrow|sans-serif"],
  ["pt serif", "PT Serif|serif"],
  ["pt serif caption", "PT Serif Caption|serif"],
  ["public sans", "Public Sans|sans-serif"],
  ["puppies play", "Puppies Play|handwriting"],
  ["puritan", "Puritan|sans-serif"],
  ["purple purse", "Purple Purse|display"],
  ["qahiri", "Qahiri|sans-serif"],
  ["quando", "Quando|serif"],
  ["quantico", "Quantico|sans-serif"],
  ["quattrocento", "Quattrocento|serif"],
  ["quattrocento sans", "Quattrocento Sans|sans-serif"],
  ["questrial", "Questrial|sans-serif"],
  ["quicksand", "Quicksand|sans-serif"],
  ["quintessential", "Quintessential|handwriting"],
  ["qwigley", "Qwigley|handwriting"],
  ["qwitcher grypen", "Qwitcher Grypen|handwriting"],
  ["racing sans one", "Racing Sans One|display"],
  ["radio canada", "Radio Canada|sans-serif"],
  ["radio canada big", "Radio Canada Big|sans-serif"],
  ["radley", "Radley|serif"],
  ["rajdhani", "Rajdhani|sans-serif"],
  ["rakkas", "Rakkas|display"],
  ["raleway", "Raleway|sans-serif"],
  ["raleway dots", "Raleway Dots|display"],
  ["ramabhadra", "Ramabhadra|sans-serif"],
  ["ramaraja", "Ramaraja|serif"],
  ["rambla", "Rambla|sans-serif"],
  ["rammetto one", "Rammetto One|display"],
  ["rampart one", "Rampart One|display"],
  ["ramsina", "Ramsina|serif"],
  ["ranchers", "Ranchers|display"],
  ["rancho", "Rancho|handwriting"],
  ["ranga", "Ranga|display"],
  ["rasa", "Rasa|serif"],
  ["rationale", "Rationale|sans-serif"],
  ["ravi prakash", "Ravi Prakash|display"],
  ["readex pro", "Readex Pro|sans-serif"],
  ["recursive", "Recursive|sans-serif"],
  ["red hat display", "Red Hat Display|sans-serif"],
  ["red hat mono", "Red Hat Mono|monospace"],
  ["red hat text", "Red Hat Text|sans-serif"],
  ["red rose", "Red Rose|display"],
  ["redacted", "Redacted|display"],
  ["redacted script", "Redacted Script|display"],
  ["reddit mono", "Reddit Mono|monospace"],
  ["reddit sans", "Reddit Sans|sans-serif"],
  ["reddit sans condensed", "Reddit Sans Condensed|sans-serif"],
  ["redressed", "Redressed|handwriting"],
  ["reem kufi", "Reem Kufi|sans-serif"],
  ["reem kufi fun", "Reem Kufi Fun|sans-serif"],
  ["reem kufi ink", "Reem Kufi Ink|sans-serif"],
  ["reenie beanie", "Reenie Beanie|handwriting"],
  ["reggae one", "Reggae One|display"],
  ["rem", "REM|sans-serif"],
  ["rethink sans", "Rethink Sans|sans-serif"],
  ["revalia", "Revalia|display"],
  ["rhodium libre", "Rhodium Libre|serif"],
  ["ribeye", "Ribeye|display"],
  ["ribeye marrow", "Ribeye Marrow|display"],
  ["righteous", "Righteous|display"],
  ["risque", "Risque|display"],
  ["road rage", "Road Rage|display"],
  ["roboto", "Roboto|sans-serif"],
  ["roboto condensed", "Roboto Condensed|sans-serif"],
  ["roboto flex", "Roboto Flex|sans-serif"],
  ["roboto mono", "Roboto Mono|monospace"],
  ["roboto serif", "Roboto Serif|serif"],
  ["roboto slab", "Roboto Slab|serif"],
  ["rochester", "Rochester|handwriting"],
  ["rock 3d", "Rock 3D|display"],
  ["rock salt", "Rock Salt|handwriting"],
  ["rocknroll one", "RocknRoll One|sans-serif"],
  ["rokkitt", "Rokkitt|serif"],
  ["romanesco", "Romanesco|handwriting"],
  ["ropa sans", "Ropa Sans|sans-serif"],
  ["rosario", "Rosario|sans-serif"],
  ["rosarivo", "Rosarivo|serif"],
  ["rouge script", "Rouge Script|handwriting"],
  ["rowdies", "Rowdies|display"],
  ["rozha one", "Rozha One|serif"],
  ["rubik", "Rubik|sans-serif"],
  ["rubik 80s fade", "Rubik 80s Fade|display"],
  ["rubik beastly", "Rubik Beastly|display"],
  ["rubik broken fax", "Rubik Broken Fax|display"],
  ["rubik bubbles", "Rubik Bubbles|display"],
  ["rubik burned", "Rubik Burned|display"],
  ["rubik dirt", "Rubik Dirt|display"],
  ["rubik distressed", "Rubik Distressed|display"],
  ["rubik doodle shadow", "Rubik Doodle Shadow|display"],
  ["rubik doodle triangles", "Rubik Doodle Triangles|display"],
  ["rubik gemstones", "Rubik Gemstones|display"],
  ["rubik glitch", "Rubik Glitch|display"],
  ["rubik glitch pop", "Rubik Glitch Pop|display"],
  ["rubik iso", "Rubik Iso|display"],
  ["rubik lines", "Rubik Lines|display"],
  ["rubik maps", "Rubik Maps|display"],
  ["rubik marker hatch", "Rubik Marker Hatch|display"],
  ["rubik maze", "Rubik Maze|display"],
  ["rubik microbe", "Rubik Microbe|display"],
  ["rubik mono one", "Rubik Mono One|sans-serif"],
  ["rubik moonrocks", "Rubik Moonrocks|display"],
  ["rubik pixels", "Rubik Pixels|display"],
  ["rubik puddles", "Rubik Puddles|display"],
  ["rubik scribble", "Rubik Scribble|display"],
  ["rubik spray paint", "Rubik Spray Paint|display"],
  ["rubik storm", "Rubik Storm|display"],
  ["rubik vinyl", "Rubik Vinyl|display"],
  ["rubik wet paint", "Rubik Wet Paint|display"],
  ["ruda", "Ruda|sans-serif"],
  ["rufina", "Rufina|serif"],
  ["ruge boogie", "Ruge Boogie|handwriting"],
  ["ruluko", "Ruluko|sans-serif"],
  ["rum raisin", "Rum Raisin|sans-serif"],
  ["ruslan display", "Ruslan Display|display"],
  ["russo one", "Russo One|sans-serif"],
  ["ruthie", "Ruthie|handwriting"],
  ["ruwudu", "Ruwudu|serif"],
  ["rye", "Rye|display"],
  ["sacramento", "Sacramento|handwriting"],
  ["sahitya", "Sahitya|serif"],
  ["sail", "Sail|display"],
  ["saira", "Saira|sans-serif"],
  ["saira condensed", "Saira Condensed|sans-serif"],
  ["saira extra condensed", "Saira Extra Condensed|sans-serif"],
  ["saira semi condensed", "Saira Semi Condensed|sans-serif"],
  ["saira stencil", "Saira Stencil|display"],
  ["saira stencil one", "Saira Stencil One|display"],
  ["salsa", "Salsa|display"],
  ["sanchez", "Sanchez|serif"],
  ["sancreek", "Sancreek|display"],
  ["sankofa display", "Sankofa Display|sans-serif"],
  ["sansation", "Sansation|sans-serif"],
  ["sansita", "Sansita|sans-serif"],
  ["sansita swashed", "Sansita Swashed|display"],
  ["sarabun", "Sarabun|sans-serif"],
  ["sarala", "Sarala|sans-serif"],
  ["sarina", "Sarina|display"],
  ["sarpanch", "Sarpanch|sans-serif"],
  ["sassy frass", "Sassy Frass|handwriting"],
  ["satisfy", "Satisfy|handwriting"],
  ["savate", "Savate|sans-serif"],
  ["sawarabi gothic", "Sawarabi Gothic|sans-serif"],
  ["sawarabi mincho", "Sawarabi Mincho|serif"],
  ["scada", "Scada|sans-serif"],
  ["scheherazade new", "Scheherazade New|serif"],
  ["schibsted grotesk", "Schibsted Grotesk|sans-serif"],
  ["schoolbell", "Schoolbell|handwriting"],
  ["science gothic", "Science Gothic|sans-serif"],
  ["scope one", "Scope One|serif"],
  ["seaweed script", "Seaweed Script|display"],
  ["secular one", "Secular One|sans-serif"],
  ["sedan", "Sedan|serif"],
  ["sedan sc", "Sedan SC|serif"],
  ["sedgwick ave", "Sedgwick Ave|handwriting"],
  ["sedgwick ave display", "Sedgwick Ave Display|handwriting"],
  ["sekuya", "Sekuya|display"],
  ["sen", "Sen|sans-serif"],
  ["send flowers", "Send Flowers|handwriting"],
  ["sevillana", "Sevillana|display"],
  ["seymour one", "Seymour One|sans-serif"],
  ["shadows into light", "Shadows Into Light|handwriting"],
  ["shadows into light two", "Shadows Into Light Two|handwriting"],
  ["shafarik", "Shafarik|display"],
  ["shalimar", "Shalimar|handwriting"],
  ["shantell sans", "Shantell Sans|display"],
  ["shanti", "Shanti|sans-serif"],
  ["share", "Share|sans-serif"],
  ["share tech", "Share Tech|sans-serif"],
  ["share tech mono", "Share Tech Mono|monospace"],
  ["shippori antique", "Shippori Antique|sans-serif"],
  ["shippori antique b1", "Shippori Antique B1|sans-serif"],
  ["shippori mincho", "Shippori Mincho|serif"],
  ["shippori mincho b1", "Shippori Mincho B1|serif"],
  ["shizuru", "Shizuru|display"],
  ["shojumaru", "Shojumaru|display"],
  ["short stack", "Short Stack|handwriting"],
  ["shrikhand", "Shrikhand|display"],
  ["siemreap", "Siemreap|sans-serif"],
  ["sigmar", "Sigmar|display"],
  ["sigmar one", "Sigmar One|display"],
  ["signika", "Signika|sans-serif"],
  ["signika negative", "Signika Negative|sans-serif"],
  ["silkscreen", "Silkscreen|display"],
  ["simonetta", "Simonetta|display"],
  ["single day", "Single Day|display"],
  ["sintony", "Sintony|sans-serif"],
  ["sirin stencil", "Sirin Stencil|display"],
  ["sirivennela", "Sirivennela|sans-serif"],
  ["six caps", "Six Caps|sans-serif"],
  ["sixtyfour", "Sixtyfour|monospace"],
  ["sixtyfour convergence", "Sixtyfour Convergence|monospace"],
  ["skranji", "Skranji|display"],
  ["slabo 13px", "Slabo 13px|serif"],
  ["slabo 27px", "Slabo 27px|serif"],
  ["slackey", "Slackey|display"],
  ["slackside one", "Slackside One|handwriting"],
  ["smokum", "Smokum|display"],
  ["smooch", "Smooch|handwriting"],
  ["smooch sans", "Smooch Sans|sans-serif"],
  ["smythe", "Smythe|display"],
  ["sn pro", "SN Pro|sans-serif"],
  ["sniglet", "Sniglet|display"],
  ["snippet", "Snippet|sans-serif"],
  ["snowburst one", "Snowburst One|display"],
  ["sofadi one", "Sofadi One|display"],
  ["sofia", "Sofia|handwriting"],
  ["sofia sans", "Sofia Sans|sans-serif"],
  ["sofia sans condensed", "Sofia Sans Condensed|sans-serif"],
  ["sofia sans extra condensed", "Sofia Sans Extra Condensed|sans-serif"],
  ["sofia sans semi condensed", "Sofia Sans Semi Condensed|sans-serif"],
  ["solitreo", "Solitreo|handwriting"],
  ["solway", "Solway|serif"],
  ["sometype mono", "Sometype Mono|monospace"],
  ["song myung", "Song Myung|serif"],
  ["sono", "Sono|sans-serif"],
  ["sonsie one", "Sonsie One|display"],
  ["sora", "Sora|sans-serif"],
  ["sorts mill goudy", "Sorts Mill Goudy|serif"],
  ["sour gummy", "Sour Gummy|sans-serif"],
  ["source code pro", "Source Code Pro|monospace"],
  ["source sans 3", "Source Sans 3|sans-serif"],
  ["source serif 4", "Source Serif 4|serif"],
  ["space grotesk", "Space Grotesk|sans-serif"],
  ["space mono", "Space Mono|monospace"],
  ["special elite", "Special Elite|display"],
  ["special gothic", "Special Gothic|sans-serif"],
  ["special gothic condensed one", "Special Gothic Condensed One|sans-serif"],
  ["special gothic expanded one", "Special Gothic Expanded One|sans-serif"],
  ["spectral", "Spectral|serif"],
  ["spectral sc", "Spectral SC|serif"],
  ["spicy rice", "Spicy Rice|display"],
  ["spinnaker", "Spinnaker|sans-serif"],
  ["spirax", "Spirax|display"],
  ["splash", "Splash|handwriting"],
  ["spline sans", "Spline Sans|sans-serif"],
  ["spline sans mono", "Spline Sans Mono|monospace"],
  ["squada one", "Squada One|display"],
  ["square peg", "Square Peg|handwriting"],
  ["sree krushnadevaraya", "Sree Krushnadevaraya|serif"],
  ["sriracha", "Sriracha|handwriting"],
  ["srisakdi", "Srisakdi|display"],
  ["staatliches", "Staatliches|display"],
  ["stack sans headline", "Stack Sans Headline|sans-serif"],
  ["stack sans notch", "Stack Sans Notch|sans-serif"],
  ["stack sans text", "Stack Sans Text|sans-serif"],
  ["stalemate", "Stalemate|handwriting"],
  ["stalinist one", "Stalinist One|display"],
  ["stardos stencil", "Stardos Stencil|display"],
  ["stick", "Stick|sans-serif"],
  ["stick no bills", "Stick No Bills|sans-serif"],
  ["stint ultra condensed", "Stint Ultra Condensed|serif"],
  ["stint ultra expanded", "Stint Ultra Expanded|serif"],
  ["stix two text", "STIX Two Text|serif"],
  ["stoke", "Stoke|serif"],
  ["story script", "Story Script|sans-serif"],
  ["strait", "Strait|sans-serif"],
  ["style script", "Style Script|handwriting"],
  ["stylish", "Stylish|sans-serif"],
  ["sue ellen francisco", "Sue Ellen Francisco|handwriting"],
  ["suez one", "Suez One|serif"],
  ["sulphur point", "Sulphur Point|sans-serif"],
  ["sumana", "Sumana|serif"],
  ["sunflower", "Sunflower|sans-serif"],
  ["sunshiney", "Sunshiney|handwriting"],
  ["supermercado one", "Supermercado One|display"],
  ["sura", "Sura|serif"],
  ["suranna", "Suranna|serif"],
  ["suravaram", "Suravaram|serif"],
  ["suse", "SUSE|sans-serif"],
  ["suse mono", "SUSE Mono|sans-serif"],
  ["suwannaphum", "Suwannaphum|serif"],
  ["swanky and moo moo", "Swanky and Moo Moo|handwriting"],
  ["syncopate", "Syncopate|sans-serif"],
  ["syne", "Syne|sans-serif"],
  ["syne mono", "Syne Mono|monospace"],
  ["syne tactile", "Syne Tactile|display"],
  ["tac one", "Tac One|sans-serif"],
  ["tagesschrift", "Tagesschrift|display"],
  ["tai heritage pro", "Tai Heritage Pro|serif"],
  ["tajawal", "Tajawal|sans-serif"],
  ["tangerine", "Tangerine|handwriting"],
  ["tapestry", "Tapestry|handwriting"],
  ["taprom", "Taprom|display"],
  ["tasa explorer", "TASA Explorer|sans-serif"],
  ["tasa orbiter", "TASA Orbiter|sans-serif"],
  ["tauri", "Tauri|sans-serif"],
  ["taviraj", "Taviraj|serif"],
  ["teachers", "Teachers|sans-serif"],
  ["teko", "Teko|sans-serif"],
  ["tektur", "Tektur|display"],
  ["telex", "Telex|sans-serif"],
  ["tenali ramakrishna", "Tenali Ramakrishna|sans-serif"],
  ["tenor sans", "Tenor Sans|sans-serif"],
  ["text me one", "Text Me One|sans-serif"],
  ["texturina", "Texturina|serif"],
  ["thasadith", "Thasadith|sans-serif"],
  ["the girl next door", "The Girl Next Door|handwriting"],
  ["the nautigal", "The Nautigal|handwriting"],
  ["tienne", "Tienne|serif"],
  ["tiktok sans", "TikTok Sans|sans-serif"],
  ["tillana", "Tillana|display"],
  ["tilt neon", "Tilt Neon|display"],
  ["tilt prism", "Tilt Prism|display"],
  ["tilt warp", "Tilt Warp|display"],
  ["timmana", "Timmana|sans-serif"],
  ["tinos", "Tinos|serif"],
  ["tiny5", "Tiny5|sans-serif"],
  ["tiro bangla", "Tiro Bangla|serif"],
  ["tiro devanagari hindi", "Tiro Devanagari Hindi|serif"],
  ["tiro devanagari marathi", "Tiro Devanagari Marathi|serif"],
  ["tiro devanagari sanskrit", "Tiro Devanagari Sanskrit|serif"],
  ["tiro gurmukhi", "Tiro Gurmukhi|serif"],
  ["tiro kannada", "Tiro Kannada|serif"],
  ["tiro tamil", "Tiro Tamil|serif"],
  ["tiro telugu", "Tiro Telugu|serif"],
  ["tirra", "Tirra|sans-serif"],
  ["titan one", "Titan One|display"],
  ["titillium web", "Titillium Web|sans-serif"],
  ["tomorrow", "Tomorrow|sans-serif"],
  ["tourney", "Tourney|display"],
  ["trade winds", "Trade Winds|display"],
  ["train one", "Train One|display"],
  ["triodion", "Triodion|display"],
  ["trirong", "Trirong|serif"],
  ["trispace", "Trispace|sans-serif"],
  ["trocchi", "Trocchi|serif"],
  ["trochut", "Trochut|display"],
  ["truculenta", "Truculenta|sans-serif"],
  ["trykker", "Trykker|serif"],
  ["tsukimi rounded", "Tsukimi Rounded|sans-serif"],
  ["tuffy", "Tuffy|sans-serif"],
  ["tulpen one", "Tulpen One|display"],
  ["turret road", "Turret Road|display"],
  ["twinkle star", "Twinkle Star|handwriting"],
  ["ubuntu", "Ubuntu|sans-serif"],
  ["ubuntu condensed", "Ubuntu Condensed|sans-serif"],
  ["ubuntu mono", "Ubuntu Mono|monospace"],
  ["ubuntu sans", "Ubuntu Sans|sans-serif"],
  ["ubuntu sans mono", "Ubuntu Sans Mono|monospace"],
  ["uchen", "Uchen|serif"],
  ["ultra", "Ultra|serif"],
  ["unbounded", "Unbounded|sans-serif"],
  ["uncial antiqua", "Uncial Antiqua|display"],
  ["underdog", "Underdog|display"],
  ["unica one", "Unica One|display"],
  ["unifrakturcook", "UnifrakturCook|display"],
  ["unifrakturmaguntia", "UnifrakturMaguntia|display"],
  ["unkempt", "Unkempt|display"],
  ["unlock", "Unlock|display"],
  ["unna", "Unna|serif"],
  ["uoqmunthenkhung", "UoqMunThenKhung|serif"],
  ["updock", "Updock|handwriting"],
  ["urbanist", "Urbanist|sans-serif"],
  ["vampiro one", "Vampiro One|display"],
  ["varela", "Varela|sans-serif"],
  ["varela round", "Varela Round|sans-serif"],
  ["varta", "Varta|sans-serif"],
  ["vast shadow", "Vast Shadow|serif"],
  ["vazirmatn", "Vazirmatn|sans-serif"],
  ["vend sans", "Vend Sans|sans-serif"],
  ["vesper libre", "Vesper Libre|serif"],
  ["viaoda libre", "Viaoda Libre|display"],
  ["vibes", "Vibes|display"],
  ["vibur", "Vibur|handwriting"],
  ["victor mono", "Victor Mono|monospace"],
  ["vidaloka", "Vidaloka|serif"],
  ["viga", "Viga|sans-serif"],
  ["vina sans", "Vina Sans|display"],
  ["voces", "Voces|sans-serif"],
  ["volkhov", "Volkhov|serif"],
  ["vollkorn", "Vollkorn|serif"],
  ["vollkorn sc", "Vollkorn SC|serif"],
  ["voltaire", "Voltaire|sans-serif"],
  ["vt323", "VT323|monospace"],
  ["vujahday script", "Vujahday Script|handwriting"],
  ["waiting for the sunrise", "Waiting for the Sunrise|handwriting"],
  ["wallpoet", "Wallpoet|display"],
  ["walter turncoat", "Walter Turncoat|handwriting"],
  ["warnes", "Warnes|display"],
  ["water brush", "Water Brush|handwriting"],
  ["waterfall", "Waterfall|handwriting"],
  ["wavefont", "Wavefont|display"],
  ["wdxl lubrifont jp n", "WDXL Lubrifont JP N|sans-serif"],
  ["wdxl lubrifont sc", "WDXL Lubrifont SC|sans-serif"],
  ["wdxl lubrifont tc", "WDXL Lubrifont TC|sans-serif"],
  ["wellfleet", "Wellfleet|serif"],
  ["wendy one", "Wendy One|sans-serif"],
  ["whisper", "Whisper|handwriting"],
  ["windsong", "WindSong|handwriting"],
  ["winky rough", "Winky Rough|sans-serif"],
  ["winky sans", "Winky Sans|sans-serif"],
  ["wire one", "Wire One|sans-serif"],
  ["wittgenstein", "Wittgenstein|serif"],
  ["wix madefor display", "Wix Madefor Display|sans-serif"],
  ["wix madefor text", "Wix Madefor Text|sans-serif"],
  ["work sans", "Work Sans|sans-serif"],
  ["workbench", "Workbench|monospace"],
  ["xanh mono", "Xanh Mono|monospace"],
  ["yaldevi", "Yaldevi|sans-serif"],
  ["yanone kaffeesatz", "Yanone Kaffeesatz|sans-serif"],
  ["yantramanav", "Yantramanav|sans-serif"],
  ["yarndings 12", "Yarndings 12|display"],
  ["yarndings 12 charted", "Yarndings 12 Charted|display"],
  ["yarndings 20", "Yarndings 20|display"],
  ["yarndings 20 charted", "Yarndings 20 Charted|display"],
  ["yatra one", "Yatra One|display"],
  ["yellowtail", "Yellowtail|handwriting"],
  ["yeon sung", "Yeon Sung|display"],
  ["yeseva one", "Yeseva One|display"],
  ["yesteryear", "Yesteryear|handwriting"],
  ["yomogi", "Yomogi|handwriting"],
  ["young serif", "Young Serif|serif"],
  ["yrsa", "Yrsa|serif"],
  ["ysabeau", "Ysabeau|sans-serif"],
  ["ysabeau infant", "Ysabeau Infant|sans-serif"],
  ["ysabeau office", "Ysabeau Office|sans-serif"],
  ["ysabeau sc", "Ysabeau SC|sans-serif"],
  ["yuji boku", "Yuji Boku|serif"],
  ["yuji hentaigana akari", "Yuji Hentaigana Akari|handwriting"],
  ["yuji hentaigana akebono", "Yuji Hentaigana Akebono|handwriting"],
  ["yuji mai", "Yuji Mai|serif"],
  ["yuji syuku", "Yuji Syuku|serif"],
  ["yusei magic", "Yusei Magic|sans-serif"],
  ["zain", "Zain|sans-serif"],
  ["zalando sans", "Zalando Sans|sans-serif"],
  ["zalando sans expanded", "Zalando Sans Expanded|sans-serif"],
  ["zalando sans semiexpanded", "Zalando Sans SemiExpanded|sans-serif"],
  ["zcool kuaile", "ZCOOL KuaiLe|sans-serif"],
  ["zcool qingke huangyou", "ZCOOL QingKe HuangYou|sans-serif"],
  ["zcool xiaowei", "ZCOOL XiaoWei|sans-serif"],
  ["zen antique", "Zen Antique|serif"],
  ["zen antique soft", "Zen Antique Soft|serif"],
  ["zen dots", "Zen Dots|display"],
  ["zen kaku gothic antique", "Zen Kaku Gothic Antique|sans-serif"],
  ["zen kaku gothic new", "Zen Kaku Gothic New|sans-serif"],
  ["zen kurenaido", "Zen Kurenaido|sans-serif"],
  ["zen loop", "Zen Loop|display"],
  ["zen maru gothic", "Zen Maru Gothic|sans-serif"],
  ["zen old mincho", "Zen Old Mincho|serif"],
  ["zen tokyo zoo", "Zen Tokyo Zoo|display"],
  ["zeyada", "Zeyada|handwriting"],
  ["zhi mang xing", "Zhi Mang Xing|handwriting"],
  ["zilla slab", "Zilla Slab|serif"],
  ["zilla slab highlight", "Zilla Slab Highlight|serif"],
]);

function parseEntry(val: string): { displayName: string; category: string } {
  const idx = val.lastIndexOf("|");
  return { displayName: val.slice(0, idx), category: val.slice(idx + 1) };
}

export function isGoogleFont(name: string): boolean {
  return GOOGLE_FONTS.has(name.toLowerCase().trim());
}

export function getGoogleFontCategory(name: string): string | null {
  const val = GOOGLE_FONTS.get(name.toLowerCase().trim());
  return val ? parseEntry(val).category : null;
}

export function getGoogleFontDisplayName(name: string): string | null {
  const val = GOOGLE_FONTS.get(name.toLowerCase().trim());
  return val ? parseEntry(val).displayName : null;
}

export function getGoogleFontsUrl(name: string, weights?: string[]): string {
  const display = getGoogleFontDisplayName(name) ?? name;
  const encoded = display.replace(/\s+/g, "+");
  const weightParam = weights && weights.length > 0
    ? ":wght@" + weights.join(";")
    : "";
  return `https://fonts.googleapis.com/css2?family=${encoded}${weightParam}&display=swap`;
}

/** Return all [key, displayName, category] triples. */
export function getAllGoogleFonts(): Array<[string, string, string]> {
  return Array.from(GOOGLE_FONTS.entries()).map(([key, val]) => {
    const { displayName, category } = parseEntry(val);
    return [key, displayName, category];
  });
}

/** Return display names of all fonts in a given category. */
export function getGoogleFontsByCategory(category: string): string[] {
  const target = category.toLowerCase().trim();
  const out: string[] = [];
  for (const [, val] of GOOGLE_FONTS) {
    const parsed = parseEntry(val);
    if (parsed.category === target) out.push(parsed.displayName);
  }
  return out;
}

export function getGoogleFontCount(): number {
  return GOOGLE_FONTS.size;
}

