// Sync with: services/playwright/src/extract-fonts.ts (SYSTEM_FONTS)

/** Normalize font name for matching: lowercase, strip quotes/spaces/hyphens */
function normalizeForMatch(name: string): string {
  return name.toLowerCase().trim().replace(/['"]/g, "").replace(/[-\s]/g, "");
}

const SYSTEM_FONTS = new Set([
  // CSS generic families
  "serif",
  "sans-serif",
  "monospace",
  "cursive",
  "fantasy",
  "system-ui",
  "ui-serif",
  "ui-sans-serif",
  "ui-monospace",
  "ui-rounded",
  "emoji",
  "math",
  "fangsong",
  // Windows core
  "arial",
  "helvetica",
  "helvetica neue",
  "times",
  "times new roman",
  "courier",
  "courier new",
  "georgia",
  "verdana",
  "tahoma",
  "trebuchet ms",
  "lucida sans",
  "lucida console",
  "lucida grande",
  "lucida sans unicode",
  "impact",
  "comic sans ms",
  "segoe ui",
  "segoe ui emoji",
  "segoe ui symbol",
  "segoe ui variable",
  "microsoft sans serif",
  "ms gothic",
  "ms pgothic",
  "meiryo",
  "yu gothic",
  "yu gothic ui",
  // Windows additional
  "calibri",
  "cambria",
  "candara",
  "constantia",
  "corbel",
  "bahnschrift",
  "microsoft yahei",
  "microsoft yahei ui",
  "simsun",
  "simhei",
  // macOS / iOS
  "-apple-system",
  "blinkmacsystemfont",
  "apple color emoji",
  "noto color emoji",
  "sf pro",
  "sf pro display",
  "sf pro text",
  "sf pro rounded",
  "sf mono",
  "sfmono-regular",
  "new york",
  "menlo",
  "monaco",
  "apple sd gothic neo",
  "pingfang sc",
  "pingfang tc",
  "pingfang hk",
  "hiragino sans",
  "hiragino kaku gothic pro",
  // Apple locale variants
  "sf pro icons",
  "sf pro ar",
  "sf pro ar text",
  "sf pro ar display",
  "sf pro gulf",
  "sf pro jp",
  "sf pro kr",
  "sf pro th",
  "sf pro sc",
  "sf pro hk",
  "sf pro tc",
  // Apple legacy/internal
  "apple legacy chevron",
  "myriad set pro",
  "apple gothic",
  "apple symbols",
  ".applesystemuifont",
  ".sfnstext",
  ".sfnsdisplay",
  ".sfui",
  // macOS additional
  "avenir",
  "avenir next",
  "optima",
  "futura",
  "baskerville",
  "gill sans",
  "osaka",
  // Linux
  "liberation sans",
  "liberation serif",
  "liberation mono",
  "dejavu sans",
  "dejavu sans mono",
  "dejavu serif",
  "noto sans",
  "noto serif",
  "noto mono",
  "ubuntu",
  "cantarell",
  "droid sans",
  "droid serif",
  "roboto",
  "fira sans",
  "oxygen-sans",
  "adwaita",
  "adwaita sans",
  "adwaita mono",
  // Monospace system fonts
  "consolas",
  "andale mono",
  "source code pro",
  // CJK
  "noto sans cjk",
  "noto serif cjk",
  "malgun gothic",
  // CJK native names (Korean)
  "apple gothic",
  "hy gulim",
  "hy dotum",
  "lexi gulim",
  "맑은 고딕",
  "돋움",
  "굴림",
  // CJK native names (Japanese)
  "ヒラギノ角ゴ pro w3",
  "ヒラギノ角ゴ pron",
  "メイリオ",
  "ＭＳ Ｐゴシック",
  "ＭＳ ゴシック",
  "游ゴシック",
  "游ゴシック体",
  // CJK native names (Chinese)
  "apple ligothic",
  "apple lisung",
  "stfangsong",
  "stkaiti",
  "stsong",
  "stxihei",
  // CSS keywords
  "inherit",
  "initial",
  "unset",
  "revert",
]);

/** Pre-compute normalized set for fast lookups */
const SYSTEM_FONTS_NORMALIZED = new Set(
  Array.from(SYSTEM_FONTS).map(normalizeForMatch)
);

export function isSystemFont(name: string): boolean {
  return SYSTEM_FONTS_NORMALIZED.has(normalizeForMatch(name));
}
