// Curated list of popular websites with notable web font usage.
// Used by pre-warm.ts to populate the cache ahead of user requests.

export const PRE_WARM_URLS: string[] = [
  // ── Design & Tech Companies ──
  "https://linear.app",
  "https://vercel.com",
  "https://stripe.com",
  "https://figma.com",
  "https://github.com",
  "https://gitlab.com",
  "https://atlassian.com",
  "https://framer.com",
  "https://webflow.com",
  "https://sketch.com",
  "https://invisionapp.com",
  "https://dribbble.com",
  "https://behance.net",
  "https://pinterest.com",
  "https://miro.com",
  "https://loom.com",
  "https://raycast.com",
  "https://craft.do",
  "https://zed.dev",
  "https://pitch.com",

  // ── SaaS & Startups ──
  "https://slack.com",
  "https://discord.com",
  "https://spotify.com",
  "https://airbnb.com",
  "https://dropbox.com",
  "https://zoom.us",
  "https://hubspot.com",
  "https://twilio.com",
  "https://airtable.com",
  "https://asana.com",
  "https://monday.com",
  "https://calendly.com",
  "https://grammarly.com",
  "https://anthropic.com",
  "https://replicate.com",
  "https://arc.net",
  "https://huggingface.co",
  "https://stability.ai",
  "https://cursor.com",

  // ── News & Media ──
  "https://substack.com",
  "https://theverge.com",
  "https://wired.com",
  "https://techcrunch.com",
  "https://arstechnica.com",
  "https://theguardian.com",
  "https://bbc.com",
  "https://cnn.com",
  "https://vox.com",
  "https://vice.com",
  "https://newyorker.com",
  "https://smashingmagazine.com",
  "https://hackernoon.com",
  "https://dev.to",
  "https://slate.com",
  "https://theatlantic.com",
  "https://polygon.com",
  "https://engadget.com",
  "https://mashable.com",
  "https://restofworld.org",
  "https://www.404media.co",

  // ── E-commerce & Brands ──
  "https://apple.com",
  "https://nike.com",
  "https://shopify.com",
  "https://amazon.com",
  "https://squarespace.com",
  "https://gumroad.com",
  "https://patagonia.com",
  "https://glossier.com",
  "https://allbirds.com",
  "https://warbyparker.com",

  // ── Developer Tools ──
  "https://supabase.com",
  "https://tailwindcss.com",
  "https://prisma.io",
  "https://astro.build",
  "https://remix.run",
  "https://nextjs.org",
  "https://turbo.build",
  "https://railway.com",
  "https://fly.io",
  "https://render.com",
  "https://deno.com",
  "https://bun.sh",
  "https://sentry.io",
  "https://svelte.dev",
  "https://nuxt.com",
  "https://tailwindui.com",
  "https://fontsource.org",

  // ── Korean Sites ──
  "https://toss.im",
  "https://www.kakaocorp.com",
  "https://www.naver.com",
  "https://line.me",
  "https://www.woowahan.com",
  "https://www.daangn.com",
  "https://www.banksalad.com",
  "https://flex.team",
  "https://channel.io",

  // ── Portfolio & Agency ──
  "https://stripe.com/press",
  "https://www.awwwards.com",
  "https://www.typewolf.com",
  "https://fonts.google.com",
  "https://rsms.me/inter",
  "https://www.fontshare.com",
  "https://www.atipofoundry.com",
  "https://klim.co.nz",
];
