Output assets/screenshots/theme-catppuccin-latte.gif

Require wtfont

Set Shell "zsh"
Set FontSize 18
Set Width 1200
Set Height 700
Set Padding 20
Set Theme "Catppuccin Latte"
Env PROMPT_EOL_MARK ""

Hide
Type "wtfont config theme catppuccin-latte"
Enter
Sleep 500ms
Type "wtfont browse sans-serif --limit 10"
Enter
Sleep 2s
Show
Sleep 1s
Screenshot assets/screenshots/theme-catppuccin-latte.png
Sleep 500ms
